### ISSUE TITLE
Consider adding horde support

### ISSUE THREAD

**Issue by Maykeye** [TavernAI/TavernAI-v1#1]
It often has GPT-NeoX-20B-Erebus model online. 

It wouldn't be the issue if I could simply point kobold client to the horde and then point tavern.ai to the kobold client, but [it's not supported](https://github.com/KoboldAI/KoboldAI-Client/blob/1dbc987048ad2126bc01c48854854ee36827f270/aiserver.py#L4440) (and crashes tavern.ai server I try to do so)

**Comment by TavernAI** [comment]
I haven't looked at how Horde works yet, but if it's possible, the Horde support will definitely be added.

**Comment by xloem** [comment]
This looks improperly closed by an unrelated change.

**Comment by MarkSchmidty** [comment]
@TavernAI This has clearly not been implemented and was closed incorrectly. Please reopen?

There's an implementation in a fork here: https://github.com/TavernAI/TavernAI/compare/main...Aspartame-e951:TavernAI:main

I've tested. It works quite nicely.
