### ISSUE TITLE
Feature Request: Supporting Author's Note in KoboldAI

### ISSUE THREAD

**Issue by astrosteve** [TavernAI/TavernAI-v1#10]
Would it be possible to support Author's Note with KoboldAI? I noticed those settings exist in server.js, but switching them to True doesn't seem to have any effect, so it seems like they're likely not implemented? I checked the prompt showing in the TavernAI window and didn't see the Author's Note anywhere, so I'm assuming it's having no effect.

**Comment by TavernAI** [comment]
A similar function is performed by "Personality summary". It is located at a depth of 8-15 messages and has a significant impact (works differently for Pygmalion). "Author's Note" variable in the code indicates whether to use Author's Note from KoboldAI GUI
