### ISSUE TITLE
Something wrong with font

### ISSUE THREAD

**Issue by equivalentx** [TavernAI/TavernAI-v1#101]
The font in 1.3.1 seems torn and thin compared to 1.2.8 and it looks way worse. Why is that and how to fix it?
![image](https://user-images.githubusercontent.com/127750474/227491614-14bba156-4b0e-4e3c-8477-0baaba7abde3.png)
![image](https://user-images.githubusercontent.com/127750474/227491645-6d5d7db6-b4de-47c6-8ff3-05c290eea8ca.png)

**Comment by Borov666** [comment]
Corrections have been made for the font weight https://github.com/TavernAI/TavernAI/commit/e3a024e8f925b27576d8a678fcf06e618f8ce1fa
