### ISSUE TITLE
Validation error when changing "Amount of generation" with NovelAI

### ISSUE THREAD

**Issue by facadefreak** [TavernAI/TavernAI-v1#102]
When I'm using any of the NovelAI models, if I set the "amount of generation" to anything other than 160, the powershell will spit out a validation error and will not add any of the text generated to the chat window. I know that it's generating the text, because I can see it in the powershell.

I'm using v1.3.1 on Windows 11.

**Comment by Borov666** [comment]
A correction has been made for the NovelAI multigen https://github.com/TavernAI/TavernAI/commit/12f82023cb82e957dcff451f88e4f8b0ca1029ae

**Comment by bucketcat** [comment]
That fix completely broke tavern ai for me. The file in question, both versions in diff view does not match the script.js in 1.3.1 release. Swapping it out, completely breaks Tavern ai. Launches into a static, blue page, with no functional UI.

Edit: Cloning main from scratch worked.

**Comment by Nexus80** [comment]
I had exactly the same issue with NovelAI. It's impossible to get NovelAI to work with TavernAI if you change amount of generation. Hope to get a working fix for this.
