### ISSUE TITLE
Not sending prompts to APIs

### ISSUE THREAD

**Issue by Talref** [TavernAI/TavernAI-v1#104]
Last pull is not working for me. No message sends prompts to any API (OAI or Kobold). This wasn't happening before the last pull.

**Comment by Talref** [comment]
This happens only on newly generated characters

**Comment by Talref** [comment]
Again, I've found that this happens if I describe my characters with this format
Char[trait1, trait2, trait3...]

Removed the [] and everything goes fine.

**Comment by aibosan** [comment]
This should be fixed now, in `7aae76cf`.
