### ISSUE TITLE
something's wrong

### ISSUE THREAD

**Issue by equivalentx** [TavernAI/TavernAI-v1#105]
after a recent update i can't get a reply, all i see is infinite loading thingie after i send a message to bot. also, for some reason, on previous version tavern stopped forgetting old tokens and just stops generating responses once 4k limit is reached
![image](https://user-images.githubusercontent.com/127750474/228067600-4f2b9210-182e-4a87-af91-ad4a08ff8f89.png)
![image](https://user-images.githubusercontent.com/127750474/228067331-3dcc0ebd-b06c-4e8a-bc0b-4e78ec628902.png)

**Comment by equivalentx** [comment]
same shit in latest 4 hours ago version
![image](https://user-images.githubusercontent.com/127750474/228166131-5e2c3cc3-661d-4b08-90f9-23544897e557.png)

**Comment by aibosan** [comment]
Are you sure you have context size set right?

**Comment by equivalentx** [comment]
idk it's maxed out as usual, i also tried reinstalling, copying only char and chats folders, same stuff
![image](https://user-images.githubusercontent.com/127750474/228211913-a7bd4436-a404-4668-b859-bfd51c07bef0.png)

**Comment by equivalentx** [comment]
oh it works fine if i lower context size, but when i put it back to max it doesnt
![image](https://user-images.githubusercontent.com/127750474/228213290-be30096b-d855-4728-bc2f-1fc4a5db7ca2.png)

**Comment by aibosan** [comment]
It seems like there's some issue with calculating token count. Try to have a bit of a margin and see how it goes.

**Comment by equivalentx** [comment]
is it a problem on my end?

**Comment by aibosan** [comment]
No, I think it might be a problem with our tokenizer. It might be counting things wrong. Or it's some sort of other issue, but I'll have to look into it. I'll keep this open in the meantime.

**Comment by equivalentx** [comment]
ok thanks

**Comment by Cohee1207** [comment]
@aibosan consider canonical OAI tokenizer usage: https://www.npmjs.com/package/@dqbd/tiktoken
