### ISSUE TITLE
Can't connect to the Tavern using node.js version "Upgrade Required"

### ISSUE THREAD

**Issue by A-Dream-Of-Illusionary-Senses** [TavernAI/TavernAI-v1#109]
I'm currently running 1.2.8 version of node.js tavern and it won't allow me to connect to the webui for some odd reason. I tried repairing node.js, and redownloding the original zip of 1.2.8. Nothing helps and it still gives me the blank white page as shown below. How can I fix this?
I want to try running "npm fund" but I don't know where to do it because it won't let me type in that powershell window.

![problem 1](https://user-images.githubusercontent.com/126984422/228245122-c8ef8769-35b0-491a-af3e-7d1d4a66c6a4.png)
![problem 2](https://user-images.githubusercontent.com/126984422/228245148-b714d686-76ef-4ee0-92d3-000a843b7db2.png)

**Comment by aibosan** [comment]
You can safely ignore the funding note.
Are you correctly trying to access the server at http://127.0.0.1:8000 ?
What browser and version are you running?

**Comment by A-Dream-Of-Illusionary-Senses** [comment]
Yes, that's the server I'm trying to connect to. It worked before and suddenly stopped after some time.
My browser is brave and it's  version is 1.49.128

**Comment by FunkEngine2023** [comment]
There's an issue with the double x-crsf token handling in 1.2.8, make sure that you are accepting same-site cookies from insecure (http, not https.) local domains, and if you are, remove all existing cookies, kill the browser and ctrl+c the tavern console, and fire them both up fresh...

1.3.1 is out, and already several commits behind Main...

**Comment by A-Dream-Of-Illusionary-Senses** [comment]
Today I launched the powershell window and it opened the tavernAI UI without any issues, and is working again. Whether it was something you guys did on the backend or this issue resolved itself somehow(I doubt that, it's probably the former). Thank you!
