### ISSUE TITLE
Feature request: Adding a way to define bot interactions with chats, CharacterAI Dumper integration?

### ISSUE THREAD

**Issue by Irelito** [TavernAI/TavernAI-v1#11]
Currently there's a decent amount of people trying to get away from Character.AI and so they are backing up their chats. Maybe it would be possible to somehow use the chats from CharacterAI to influence the bots through TavernAI? Something similar to CharacterAI's "Definition" setting basically, where you can put in example conversations.

There is also one script that has been passed around which exports CharacterAI conversations into .json scripts: https://github.com/0x000011b/characterai-dumper

If there would be a way to either use the dumper or have a custom method to add conversations in a similar way it could definitely improve the chatting experience.

**Comment by TavernAI** [comment]
CAI Chat import function added
