### ISSUE TITLE
Change function of enter key on character edit panel, and advanced edit popup (Create character.) to insert newlines instead of sending a prompt. (Automatically interpret 'Enter' as 'Shift+Enter' whenever cursor is not in the 'Type a message...' box.)

### ISSUE THREAD

**Issue by facadefreak** [TavernAI/TavernAI-v1#112]
Currently, pressing enter while using the W++ editor instantly creates the character. I've prematurely created multiple characters because of this. I think it would be more intuitive for it to either create a new entry in the editor, or do nothing at all.

**Comment by FunkEngine2023** [comment]
I am in agreement that we should not be sending the prompt when in the menus, although I will still hit shift+enter even afterwards from 28 years of learned muscle reflex when editing fields in an HTML form field submitting the whole form. (lol.)


Normally my first question would have been 'Why are you doing anything besides Ctrl+a, Ctrl+x and Ctrl+v in the character editing panels?' But I realize that a lot of our new users have zero prior coding experience and are blissfully unaware of the joy and happiness that proper coding editors provide with syntax highlighting and brackets checking... So I'll extend the olive branch and make TavernAI not punish new users with sent prompts, and suggest @facadefreak think about choosing (choose wisely!) one of the many quality coding editors to use for their major character data editing.
