### ISSUE TITLE
convert to png

### ISSUE THREAD

**Issue by equivalentx** [TavernAI/TavernAI-v1#117]
how do i convert all my bots back to png? i change webp to png in config file but it only converts first 48 bots in the folder. and after i move these 48 converted bots from the folder it still doesn't convert everything else. even after reinstalling. i just don't get it pls help

**Comment by FunkEngine2023** [comment]
Go to config.conf and change characterFormat = 'webp'; to png and put an empty file called update.txt in your/public/characters folder.  All exported characters will be in the chosen format from config.conf regardless of how they are stored in the folder.

**Comment by equivalentx** [comment]
nothing changed
![image](https://user-images.githubusercontent.com/127750474/229265693-93a5593c-05fb-4cb1-815d-979bfa687553.png)
![image](https://user-images.githubusercontent.com/127750474/229265719-ce41daec-1848-4af3-b08b-5851eac64989.png)

**Comment by FunkEngine2023** [comment]
> nothing changed ![image](https://user-images.githubusercontent.com/127750474/229265693-93a5593c-05fb-4cb1-815d-979bfa687553.png) ![image](https://user-images.githubusercontent.com/127750474/229265719-ce41daec-1848-4af3-b08b-5851eac64989.png)

I should have specified that you need to take the first 48 out and it will convert the next 48, repeat(closing the console, adding update.txt to the character folder taking the 48 png files out, 
running start.bat) as necessary until all your characters have been png-ed. Then put all your characters back into /characters.

**Comment by FunkEngine2023** [comment]
![image](https://user-images.githubusercontent.com/123712145/229265969-e5df824b-fc68-4281-82ab-c46ce12cc89e.png)
you should see this each time when it starts.  Of course your list of conversions will be... much longer... than mine.

**Comment by equivalentx** [comment]
it's the same, i move these 48 chars and chats, but it doesn't convert everything else anyway. it's like it knows i had these 48 in the folder before

but then i added letter "a" at the start of one of unconverted char's name and it converted this one char. maybe it cuts off alphabetically, around letter L

then i tried converting all the characters again and it converted 49 instead of 48 including the one with "a"

also if i put "png" into config but there's webp characters in the folder that it can't convert (48+) the console just closes after converting these 48, but if i put "webp" and there's png characters in the folder (i tried around 100) it converts all of them just fine and doesn't close

i just don't know i'm not a coder

**Comment by FunkEngine2023** [comment]
In windows explorer, view->details view->choose details add date modified to the list by scrolling down and ticking the box hit OK and fiddle the date modified column to sort by modified time.  Is it running through the characters in alphabetical order? If so what is the full name of the last file it modified and what is the full name of the next character that it should have converted but didn't?

There have been some recent changes to sanitize certain inputs like filenames etc and it's possible but not likely that one of your characters has an illegal string in the name.

If there are only .webp in the folder and config is set to .png and update.txt is present it will attempt conversion.  If no files are converted then there is something wrong with the filename of the first one that it tries to convert...

You can try narrowing things down by taking everything but 20 characters and update.txt out of the folder and converting batches of 20 until you hit one that won't convert or didn't completely convert. Determine which 10 won't convert, then take 5 out, figure out which won't convert, and try each one of the last 5 until you have just the one that refuses to convert make a copy of it and change the filename (character name is stored internally regardless of filename.)

If it still doesn't convert, then you'll have to share the file with one of us to replicate the issue and see why it's causing the problem, or if you prefer not to share the character, you will just have to leave it as the one webp character but all the rest are png...


Final thought is that you can try exporting said character once identified and it should come out as png and you can just swap the file...

**Comment by FunkEngine2023** [comment]
Additionally, re reading your comment... You did make a new update.txt for the second run right? It deletes the file automatically to clear the flag to update, so if you didn't put another update.txt file in before you restarted start.bat it's not going to reprocess the directory.

**Comment by equivalentx** [comment]
oh it's solved. the lucy west character on the screenshot had "illegal string" in it's name it seems like

thanks for the help

btw it doesnt delete the update.txt file at all

also even it's just this lucy west character the console closes if i attempt to convert it to png, i even tried rewriting the name

![image](https://user-images.githubusercontent.com/127750474/229280329-698fb356-aa05-4ffd-94db-115c6a39ca07.png)

**Comment by FunkEngine2023** [comment]
Do us a favor and select the file, hit F2, copy with ctrl+c and paste it between two backticks (`) in a reply so it shows up as a code section 

`like this` so we can see what weird unicode character it contains, or if there's some silly left shift character shenanigans going on. (Related to why we're sanitizing inputs.)

As to update.txt yeah I failed to notice that update.txt was deprecated as the trigger in a recent release. Obviously you can delete it now as well.

Really curious about what's causing server.js to have a fit though, hopefully we'll find something interesting with the actual characters(as in text glyphs) that are in the filename.  Otherwise it's just a fluke for now. 

Thanks for following up with me on this whole thing, and I'm glad that my suggestion to narrow things down until the actual problem revealed itself panned out successfully.

**Comment by equivalentx** [comment]
`Lucy West`
`Lucy West1`

btw if i update tavern what folder or file do i need to copy besides characters and chats to transfer my settings?

also autoconnect to the last api on openai doesn't work, and it would be nice to be able to have multiple characters in one chat

**Comment by FunkEngine2023** [comment]
> `Lucy West` `Lucy West1`
> 
> btw if i update tavern what folder or file do i need to copy besides characters and chats to transfer my settings?

You sort of have to manually merge the values from your 
settings.json(/public) into the appropriate spots in the new version, as frequently there are new things added that you won't have a value for in the old one so you just copy the stuff you have like avatar name presets values etc.  Same idea for config.conf(/) copy your values over for port autostart etc. And then it's just /characters /chats /notes /User Avatars and if you added backgrounds yourself /backgrounds 

I usually just zip up the whole folder before upgrading and only bother moving the /characters folder over along with editing settings settings.json and config.conf and chucking my avatar into the folder when upgrading.  Then as I want to continue old chats with a character I go dig it out of the zip file.  Saved conversations (or a lack thereof) have zero influence on the AI, and realistically anything more than 10 messages up also has zero influence on the AI.  Don't feel any need to save chats.

**Comment by FunkEngine2023** [comment]
I don't see any shenanigans in the filename, if you don't have any privacy concerns I'd love to get the actual file(s) just zip them first so that github doesn't try sanitizing them in the process.

**Comment by equivalentx** [comment]
ok thanks for the help

if i have the character doesn't mean i like it just sayin :)

[123.zip](https://github.com/TavernAI/TavernAI/files/11129325/123.zip)

and one more thing, does it really need to disconnect from api when i delete the character from tavern? it's a little annoying

**Comment by FunkEngine2023** [comment]
It shouldn't be disconnecting on delete if you're on the latest version (1.3.1+)  I just tried it out and no disconnecting, but I do recall that being an issue in the past.

Go to settings and turn on Auto-connect in the master settings section.

**Comment by equivalentx** [comment]
ok, i will update later and try it, thanks

**Comment by equivalentx** [comment]
nope, yesterday's version still disconnects when deleting a bot and doesn't reconnect on restart
![image](https://user-images.githubusercontent.com/127750474/229338598-bb5d6fa0-4d39-4bdb-a0a9-174e063cdb59.png)
