### ISSUE TITLE
[Feature Request]: support Markdown syntax

### ISSUE THREAD

**Issue by coyude** [TavernAI/TavernAI-v1#118]
I often use ChatGPT to help me solve coding problems. However, the support for Markdown syntax on TavernAI is not very good. I hope TavernAI can also support Markdown well, just like in the picture.
Thank you!

![mark](https://user-images.githubusercontent.com/24607145/229257117-dac970e4-00bf-4cca-b86d-b8cddedc9db7.jpg)

**Comment by Borov666** [comment]
Code support was added in 1.4.0
