### ISSUE TITLE
Bug Report: Generating multiple times on Pygmalion Experiment 5

### ISSUE THREAD

**Issue by TarotFooling** [TavernAI/TavernAI-v1#12]
When using Pygmalion Experiment 5 (V6) on TavernAI, it seems to generate multiple responses for one message, leading the bot to go on wild tirades.

Full log: https://pastebin.com/d6z2Nsxf

Steps to reproduce, load Pygmalion-6B V6, this can be found on huggingface under the dev branch. Then just generate a response to a prompt.

**Comment by TavernAI** [comment]
Problem solved in 1.2.3
