### ISSUE TITLE
No web page pops up after opening the start.bat

### ISSUE THREAD

**Issue by joshx013** [TavernAI/TavernAI-v1#120]
C:\Users\joshx\Downloads\TavernAI-main>call npm install
[##################] | reify:exifreader: timing reifyNode:node_modules/uuid Completed in 530ms

**Comment by FunkEngine2023** [comment]
If autolaunch is set to false, no page pops up....

Does your powershell look like this thought?  WHen it completes...

![image](https://user-images.githubusercontent.com/123712145/229591870-bc519560-55aa-47fb-8358-34ebce8edb19.png)

**Comment by joshx013** [comment]
i don't know what is this means
![image](https://user-images.githubusercontent.com/129766727/229596011-12bcf22e-09fb-4836-aef5-1d364da6a5f9.png)

**Comment by joshx013** [comment]
i don't know what's this means
![image](https://user-images.githubusercontent.com/129766727/229596416-af4cee95-3344-44a9-8069-e5c4c7092c6d.png)

**Comment by joshx013** [comment]
after that it disappeared...i tried many times but nothing happened

**Comment by joshx013** [comment]
> If autolaunch is set to false, no page pops up....
> 
> Does your powershell look like this thought? WHen it completes...
> 
> ![image](https://user-images.githubusercontent.com/123712145/229591870-bc519560-55aa-47fb-8358-34ebce8edb19.png)

>i have no idea about this
>
![image](https://user-images.githubusercontent.com/129766727/229597064-0eca71e0-e02e-41a6-b0ad-e56b4769614c.png)
after this it disappeared

**Comment by FunkEngine2023** [comment]
type start.bat and hit enter.

start.bat is two operations. First is `call npm install` then it goes `node server.js` to actually start what it built.
