### ISSUE TITLE
ForbiddenError: invalid csrf token

### ISSUE THREAD

**Issue by Roerib** [TavernAI/TavernAI-v1#121]
![image](https://user-images.githubusercontent.com/129540827/229654192-d7ec03ce-c8db-4cd6-953d-aa37a652b060.png)

Can't upload or access characters![20230403_205125.png](https://user-images.githubusercontent.com/123712145/229658468-5421aef7-45b5-482b-9aa2-4a81a07617cb.png)

**Comment by Roerib** [comment]
My PC's clock was messed up

**Comment by FunkEngine2023** [comment]
You have another TavernAI tab still open in your browser or alternatively, you still have a zombie process (either node or npm)  clinging to life in the background. 

The third thing is clear your cookies for 127.0.0.1 as well as local host. Make sure that your browser is permitting not only cookies but insecure connections to localhost/127.0.0.1.

Based on how it literally screams, 'not even once!' right outta the gate. I am going to say there's still a TavernAI running on your machine.


So close your powershell(s), check task manager for processes named node.exe, npm.exe

I doubt it was the clock...


But for anyone else having crsf token issues, check for zombie conhost.exe, cmd.exe, and node.exe and terminate as appropriate. 


When grabbing screen shots, pressing the windows key + shift + S brings snipping tool up in the select an area to capture mode...


 Print screen and paste also works,  but we all get to see things in the margins if you like.
