### ISSUE TITLE
It crashes a lot and sometimes initialization is too long at it lasts for like 6 hours.

### ISSUE THREAD

**Issue by lonelyshit** [TavernAI/TavernAI-v1#122]

**Comment by swapneils** [comment]
Initialization has worked fine for me, but I agree re: crashing; when models take 20-30 min to respond, as is often the case on low-quality hardware, the TavernAI backend often just closes without warning, requiring a full restart.

Not to mention, the WebUI has no indication that this has occurred, so you're stuck trying to connect for 30+ min until you notice that the terminal window has disappeared.
