### ISSUE TITLE
Crashes after inputting Kobold API URL

### ISSUE THREAD

**Issue by Neverdusk** [TavernAI/TavernAI-v1#128]
I've been using TavernAI alongside Oobabooga, but I wanted to try using it with a Kobold Colab since it would be much faster. However, after inserting the Kobold url in the API slot and pressing connect, the TavernAI command prompt closed by itself. 

Now, whenever I try to open TavernAI, the command prompt closes after a few moments, and I'm unable to use it at all. This happened previously and was fixed by a reinstallation, but now it's happened again - so I believe it's consistent. Somehow using a Kobold API url just breaks TavernAI completely. 

Edit: I was able to stop it from crashing on open by going into the settings file and deleting the API value. However, this doesn't resolve it crashing after putting in a Kobold API url.

**Comment by aibosan** [comment]
Can you run `start.bat` in a standalone command prompt window to see what the error is?
([How to open cmd in a specific location](https://stackoverflow.com/questions/60904/how-can-i-open-a-cmd-window-in-a-specific-location#:~:text=Open%20any%20folder%20on%20windows,type%20cmd%20and%20press%20enter))

**Comment by Neverdusk** [comment]
Sorry, can you tell me where to find start.bat? My installation of TavernAI only has the TavernAI application .exe, and searching the directory for start.bat didn't have any results.
