### ISSUE TITLE
Dockerfile not working.

### ISSUE THREAD

**Issue by ufxpri** [TavernAI/TavernAI-v1#130]
I'm using a Linux server for tavernAI
but the docker file won't work at all.

![image](https://user-images.githubusercontent.com/24621825/232057820-62eafe9f-f18c-4036-8314-8b2b65b8ed4b.png)

We need an explanation of why the symlink is needed so that others can decide whether to delete or improve the line.

**Comment by luisbrandao** [comment]
I have the same issue.
i BELIVE the ${APP_HOME}/config should be either a localmount (-v) or a volume.

**Comment by luisbrandao** [comment]
docker run -v $(pwd)/config:/home/node/app/config -p 8000:8000 -it tavernia:1.3.1-1
