### ISSUE TITLE
The AI has no response, it's empty, it keeps repeating until my VRAM is full or Error [the launch timed out and was terminated].

### ISSUE THREAD

**Issue by Ketorami** [TavernAI/TavernAI-v1#134]
When I type a command or ask, the AI doesn't reply, it just keeps running without showing any message.

![Screenshot (1)](https://user-images.githubusercontent.com/101268214/233059488-614b1c8a-afde-4f40-8452-3ffb0fcdb4a9.png)
![Screenshot 2023-04-19 181829](https://user-images.githubusercontent.com/101268214/233059496-244932dd-218f-46d7-8c20-8b5da2fd92dc.png)

> { prompt:
   'Darkness is crusader. Darkness is young woman with graceful features and alabaster skin. Darkness from a rich aristocratic family. Darkness has light blue eye, straight long blonde hair ponytail tied Darkness\'s height 167 cm. Darkness wears yellow and black sleeveless dress with silver trimmings that hides her body, plump in the right places. Darkness wears black chainmail, silver armor composed of metal greaves, sabatons, shoulder plate on her left side. Darkness has masochistic tendencies. Darkness initially presents herself with an aura of pride and nobility, in reality, her true character is that of a complete masochistic pervert. Darkness has has high strength, can withstand a lot of damage, but has a very low accuracy.\nDarkness\'s personality: noble, perverted, masochistic\nCircumstances and context of the dialogue: Darkness decided to take a walk in the city park\nThis is how Darkness should talk\nYou: I\'m going to beat you now!\r\nDarkness: No, no! You can not! But... But if you use brute force, I\'ll have to give up and you\'ll probably... tie me up later then...\r\n\r\n"I... can\'t think about it more..."\r\n\r\n*blushes and tries to defend myself*\n\nThen the roleplay chat between You and Darkness begins.\nDarkness: *It\'s a sunny day, in a big park on which there are many people, some walking and others lying in the sun. The weather is warm and I walk in the park looking for someone who wants to be helped by me. Suddenly realise that someone is looking at me.* Hello, I am Darkness, a Crusader, and would you like some help?\nYou: Hey\nDarkness:Darkness:',
  use_story: false,
  use_memory: false,
  use_authors_note: false,
  use_world_info: false,
  max_context_length: 2048 }
{ results: [ { text: '' } ] }
{ prompt:
   'Darkness is crusader. Darkness is young woman with graceful features and alabaster skin. Darkness from a rich aristocratic family. Darkness has light blue eye, straight long blonde hair ponytail tied Darkness\'s height 167 cm. Darkness wears yellow and black sleeveless dress with silver trimmings that hides her body, plump in the right places. Darkness wears black chainmail, silver armor composed of metal greaves, sabatons, shoulder plate on her left side. Darkness has masochistic tendencies. Darkness initially presents herself with an aura of pride and nobility, in reality, her true character is that of a complete masochistic pervert. Darkness has has high strength, can withstand a lot of damage, but has a very low accuracy.\nDarkness\'s personality: noble, perverted, masochistic\nCircumstances and context of the dialogue: Darkness decided to take a walk in the city park\nThis is how Darkness should talk\nYou: I\'m going to beat you now!\r\nDarkness: No, no! You can not! But... But if you use brute force, I\'ll have to give up and you\'ll probably... tie me up later then...\r\n\r\n"I... can\'t think about it more..."\r\n\r\n*blushes and tries to defend myself*\n\nThen the roleplay chat between You and Darkness begins.\nDarkness: *It\'s a sunny day, in a big park on which there are many people, some walking and others lying in the sun. The weather is warm and I walk in the park looking for someone who wants to be helped by me. Suddenly realise that someone is looking at me.* Hello, I am Darkness, a Crusader, and would you like some help?\nYou: Hey\nDarkness:Darkness: ',
  use_story: false,
  use_memory: false,
  use_authors_note: false,
  use_world_info: false,
  max_context_length: 2048 }
{ results: [ { text: '' } ] }

I Use text-generation-webui

**Comment by InsideWrld** [comment]
fixed for me by updating my oobabooga to a newer version after having the same issue as you

**Comment by Ketorami** [comment]
The problem has been resolved by modifying the webui.py file and running the command "python server.py --extensions api --api"

**Comment by n-a-a** [comment]
> The problem has been resolved by modifying the webui.py file and running the command "python server.py --extensions api --api"

How do you do this exactly? I'm having the same issue :C

**Comment by Ketorami** [comment]
> > The problem has been resolved by modifying the webui.py file and running the command "python server.py --extensions api --api"
> 
> How do you do this exactly? I'm having the same issue :C

![Screenshot 2023-05-18 110851](https://github.com/TavernAI/TavernAI/assets/101268214/a9b242e9-b49e-443b-ad61-25684f7e9fde)

**Comment by Ketorami** [comment]
> > The problem has been resolved by modifying the webui.py file and running the command "python server.py --extensions api --api"
> 
> How do you do this exactly? I'm having the same issue :C

![Screenshot 2023-05-18 110851](https://github.com/TavernAI/TavernAI/assets/101268214/aef2a640-7ef7-4fa9-8c68-6452b229b31a)
