### ISSUE TITLE
Improve character display

### ISSUE THREAD

**Issue by Userbingd** [TavernAI/TavernAI-v1#138]
Would it be possible to make it to where you can display the entire character library. I find it really hard to find new characters when the front page is mostly random.

**Comment by LazerCuber** [comment]
I agree, its better if they can create like a character hub or smth so that I don't need to manually click to the list of characters 😂

**Comment by Borov666** [comment]
The first line is currently occupied by the last loaded characters. Also, the categories are now clickable and you can see a more detailed list of characters. This applies to the last uploaded characters too. Categories are still being worked out.

**Comment by InsideWrld** [comment]
How do you Even get to the Main Character Display Homepage? the only way I can seem to access it at the moment is by trying to edit one of the 3 default Characters and using the advanced editor :/
