### ISSUE TITLE
Immediate crash after choosing character.

### ISSUE THREAD

**Issue by Pavelgon4ik** [TavernAI/TavernAI-v1#146]
Good day to you. 
Switched to new version of TavernAI V1.4.0 recently, I'm running TavernAI locally on my computer, when I try choose character it immediately crashes. 
![image](https://user-images.githubusercontent.com/61659850/235322863-733529f2-14a3-40a4-bdcc-6a463a273cb6.png)
(Old versions working as intented.)

UPD: Fixed it by creating a folder "Chats" in "Public", which it cannot create by itself for some reason.

**Comment by Borov666** [comment]
Fixed https://github.com/TavernAI/TavernAI/commit/a9e8c2fdcade634ae1950451044988a7640ecb87
