### ISSUE TITLE
New version 1.4.0 has no respect to the config file

### ISSUE THREAD

**Issue by benfy95** [TavernAI/TavernAI-v1#147]
As title, after editing the config file, it launches without following any parameters that I have set in the config file, for example I set to autorun false and port number 9000, it just launches with default setting. This does not happen on version 1.3.1.

**Comment by Eagle3820** [comment]
Same thing happens to me.  I tried adding an IP as a whitelist, didn't work.  I tried changing the port, still launches with the default port of 8000.  This is an issue for me since I run this on a server PC but can't connect to Tavern.AI on the device I use.

**Comment by MADjrb8u** [comment]
Was having this issue. Cloning the repo and running start.bat will respect the config file. For some reason, the exe isn't doing this.

**Comment by Borov666** [comment]
Fixed in https://github.com/TavernAI/TavernAI/commit/2aa9442ef71cd9db82625121d9af594517c1a772
Win .exe file has been updated
