### ISSUE TITLE
Please optimize and improve displays for text

### ISSUE THREAD

**Issue by LazerCuber** [TavernAI/TavernAI-v1#149]
![image](https://user-images.githubusercontent.com/113417931/235340497-319cca9a-ee5c-4e4b-a23b-240a762c4f76.png)

Like what the hell is this

**Comment by Borov666** [comment]
Yes, other designs require some refinement

**Comment by Borov666** [comment]
Fixed in https://github.com/TavernAI/TavernAI/commit/6083c7b740d5cdb66c32cc1b2487c22def48977f
