### ISSUE TITLE
1.4.0 can't connect

### ISSUE THREAD

**Issue by pp2020412** [TavernAI/TavernAI-v1#150]
1.40 i can't connect to novel ai but 1.3 is ok. In addition, I am at the25$ level, but I still can't use other models.

**Comment by Borov666** [comment]
I checked, in 1.4 the NovelAI works fine. Perhaps the api key was entered incorrectly. Did I understand correctly that you are not getting a green connection indicator?

**Comment by pp2020412** [comment]
> 

I copied and pasted the api, and I can still use 1.3 now. By the way, it seems that the krake model doesn't seem to get a reply. I am opus subscribed.

**Comment by roseyyy2022ai** [comment]
I'm trying to use KoboldAi and am running on colab. It just doesn't give me the api link (in the code output) and the website is just stuck saying, "initialization...."
Any possible fixes??

**Comment by Borov666** [comment]
1.4 still doesn't work for you?
