### ISSUE TITLE
TavernAI not launching?

### ISSUE THREAD

**Issue by swzannah** [TavernAI/TavernAI-v1#151]
I've downloaded the 1.4 update and when I try to run the batch file. It gets to about this point and then fails. I've deleted and redownloaded everything this morning, but not sure what is happening.
![Screenshot (56)](https://user-images.githubusercontent.com/21226626/235369664-98c12ba2-fdf8-4e50-a71c-8af975aa8fb8.png)

**Comment by Borov666** [comment]
It doesn't give out any more errors? So it's pretty hard to tell what the problem is.

**Comment by swzannah** [comment]
I took these two screen shot before the command prompt terminated the program on its own. Is this more helpful?
![Screenshot (57)](https://user-images.githubusercontent.com/21226626/235406131-d8c2d59b-4d9b-4b6c-b5cb-409002dc6772.png)
![Screenshot (58)](https://user-images.githubusercontent.com/21226626/235406139-a316fb07-5beb-4f55-8c83-1c3512614032.png)

**Comment by roseyyy2022ai** [comment]
Okayyyy everything is falling apart. On colab as well. No API key provided (no kobld link shown in the code output), KoboldAi seems to not be starting... (I'm trying to run it with Pygmalion 7B)....
They're really trying to kill off everything AI related.....!?

**Comment by Borov666** [comment]
Regarding the screenshots, it looks like nmp can't connect to the server with modules. Perhaps the provider is blocking it or something else.

Colab was in the process of updating, so it might not work.
