### ISSUE TITLE
SFW Version for Kids or at Work?

### ISSUE THREAD

**Issue by chigkim** [TavernAI/TavernAI-v1#153]
I just tried the Colab notebook, but most of them are NSFW.
Is there a version that you can play with kids or show your coworkers?

**Comment by pp2020412** [comment]
character.ai

**Comment by pp2020412** [comment]
character.ai，They firmly believe that they are high-spirited people, and you can use their services.

**Comment by roseyyy2022ai** [comment]
Guys!!! Kobold ai link isn't showing and the website is stuck what did I break????? (Attempting to run with Pygmalion 7b on Google colab)

**Comment by roseyyy2022ai** [comment]
> I just tried the Colab notebook, but most of them are NSFW. Is there a version that you can play with kids or show your coworkers?

Maybe try developing a character (I believe you can do that in the interface itself. Haven't tried it myself yet cuz mine just decided to break out of nowhere) that is SFW or using a filtered model (like StableVicuna, recommended btw 💯)
