### ISSUE TITLE
button disappears

### ISSUE THREAD

**Issue by pp2020412** [TavernAI/TavernAI-v1#155]
I can now connect to 1.40, as a tar version. But now there seems to be a problem with the online character selection... I click on the arrow to the right of the character, but then it disappears!

**Comment by Borov666** [comment]
Can you send a screenshot? It is not entirely clear what it is about.

**Comment by pp2020412** [comment]
> 你可以发送截图吗？目前尚不完全清楚它是关于什么的。
I found that the problem seems to have been solved again This may be due to our unique network environment here. i 'm sorry
