### ISSUE TITLE
In the collab, the KoboldAI link isn't showing. The website is just stuck saying "initialization...."

### ISSUE THREAD

**Issue by roseyyy2022ai** [TavernAI/TavernAI-v1#157]
![image](https://user-images.githubusercontent.com/122406301/235761398-2ed97b37-a28c-4350-9274-594085451d21.png)

**Comment by Borov666** [comment]
Google Colab has been updated to version 1.4.0
Perhaps there were technical works at that moment, another reason is that you have run out of the daily limit for using Colab.

**Comment by roseyyy2022ai** [comment]
> Google Colab has been updated to version 1.4.0 Perhaps there were technical works at that moment, another reason is that you have run out of the daily limit for using Colab.

No because it works when I try to load the preprogrammed models but not the Pygmalion7B or 6B

**Comment by Borov666** [comment]
There are no Pygmalion models in the official Colab of TavernAI. Perhaps you are trying to use some other Colab notebook.
