### ISSUE TITLE
[Crash] v-1.4.0 - Instant Crash after a few minutes

### ISSUE THREAD

**Issue by AsaTyr2018** [TavernAI/TavernAI-v1#158]
Good day, i just downloaded the latest release. (1.4.0)
looks really well and started up without an issue. but after some chats the tavern just crash away.
No error Message or something to trace back for me. 

I´m Using Obabooga as backend and mayaeary_pygmalion-6b-4bit-128g as model.
Befor this i used 1.3.1 and it runs very well. no crashes or so. 

Anyway to get a debug mode so i can supply you with some logs?

And i´m using windows 11 Enterprise (22H2). All requirements are at the latest patch version. 
As GPU i´m Using an rtx 3090. 24gb vram. so no bottleneck there.

**Comment by Borov666** [comment]
To get an error, run TavernAI through the console using the command: _node server.js_

**Comment by AsaTyr2018** [comment]
> 

i did. the crazy thing is now its working flawless o.o i tried the chat with Alana Sang and i just needed to write a word and it crashed. strange world xD
