### ISSUE TITLE
As the title.....The AI seems to have brought the text that calls the novel...I pulled the repetition penalty to 1.5.

### ISSUE THREAD

**Issue by pp2020412** [TavernAI/TavernAI-v1#159]
![QQ截图20230504214616](https://user-images.githubusercontent.com/66078084/236225358-12beb6c7-037a-4682-aa27-04c10424155f.png)

**Comment by pp2020412** [comment]
This is a text that is completely unsuitable for dialogue, much like the unprocessed output of novel ai.

**Comment by Borov666** [comment]
Depending on the models, sometimes this can happen. Especially if models are used that were originally created for writing stories.
