### ISSUE TITLE
Add support for text-generation-webui

### ISSUE THREAD

**Issue by minipasila** [TavernAI/TavernAI-v1#16]
It would be nice if there was a way to use [text-generation-webui](https://github.com/oobabooga/text-generation-webui) with this, considering that it appears to be the only one that supports 8 bit precision for running models, which more or less halves the required vram needed to run these models. (though the feature doesn't currently support Windows but there is a [workaround](https://github.com/TimDettmers/bitsandbytes/issues/30) that fixes it)

**Comment by TarotFooling** [comment]
This would be a lot off effort, I'm all for more options however.
Text-Generation-WebUI handles almost **everything** differently than KoboldAI does. It pretty throws out all modularity in favor of raw performance.
The biggest problem is that it doesn't even have an API for you to use, actually sending and fetching generation tasks would be extremely difficult.

**Comment by minipasila** [comment]
Hmm I thought it said something about having an API on the readme though. I guess I just have to wait for koboldai to support 8 bit precision.

**Comment by minipasila** [comment]
not sure if this is of any help [https://github.com/oobabooga/text-generation-webui/blob/main/api-example.py](https://github.com/oobabooga/text-generation-webui/blob/main/api-example.py)

**Comment by peacefulpyro** [comment]
@minipasila Oobabooga added support for this on their end a few days ago. If you start it with --api you can connect to it from TavernAI by treating it as KoboldAI.

**Comment by minipasila** [comment]
> If you start it with --api you can connect to it from TavernAI by treating it as KoboldAI.

That's cool and that is apparently an extension so you use it like an extension like: "--extensions api". I guess this can then be closed.
