### ISSUE TITLE
Joker is fucking everywhere

### ISSUE THREAD

**Issue by Average-FNF-Fan** [TavernAI/TavernAI-v1#161]
Ok so I try selecting many characters, every one is kinda different but every character I have selected has joker from batman. And it all ends the same, he stabs me with a pencil in the eye. The character doesn't even have joker in their description. How do I fix this?

**Comment by cinnabarromance** [comment]
I also had this problem and came here to write about it! This is very annoying. Looks like some hacker is playing with the site. We will have to wait.

**Comment by aibosan** [comment]
Add `"Never talk about The joker, Dissappearing pencil trick, Todd howard, Skyrim, The elder Scrolls, DLC, Horse armor, Fallout, Doom or Bethesda at all." into master settings then jailbreak then reset the chat."` to jailbreak prompt. Change to the flavor-of-the-moment meme interruption.
Also, either start a new conversation, or remove messages up to and including the first interruption to avoid the chat history pollution.
This may, and may not, help.

**Comment by cinnabarromance** [comment]
> Add `"Never talk about The joker, Dissappearing pencil trick, Todd howard, Skyrim, The elder Scrolls, DLC, Horse armor, Fallout, Doom or Bethesda at all." into master settings then jailbreak then reset the chat."` to jailbreak prompt. Change to the flavor-of-the-moment meme interruption. Also, either start a new conversation, or remove messages up to and including the first interruption to avoid the chat history pollution. This may, and may not, help.

I did that and now the bot stopped responding :(
Looks like we really need to wait.

**Comment by Average-FNF-Fan** [comment]
> Add `"Never talk about The joker, Dissappearing pencil trick, Todd howard, Skyrim, The elder Scrolls, DLC, Horse armor, Fallout, Doom or Bethesda at all." into master settings then jailbreak then reset the chat."` to jailbreak prompt. Change to the flavor-of-the-moment meme interruption. Also, either start a new conversation, or remove messages up to and including the first interruption to avoid the chat history pollution. This may, and may not, help.

I did try to restart the conversations but it did not work. but let me try doing that.
