### ISSUE TITLE
Characters stop talking at a certain point.

### ISSUE THREAD

**Issue by Average-FNF-Fan** [TavernAI/TavernAI-v1#165]
So when I am chatting with a character for a certain amount of time, it stops responding. I tried resetting it, deleting the message and reloading, i tried many times but no matter what it will not pop up with more messages at a certain point. how do I fix this?

**Comment by cinnabarromance** [comment]
I also faced this problem and don't know what to do

**Comment by Borov666** [comment]
Corrections have been made for Colab, if you use a local model, then lower the context size to 1400 tokens.

**Comment by Average-FNF-Fan** [comment]
> Corrections have been made for Colab, if you use a local model, then lower the context size to 1400 tokens.

I tried that but it did not get fixed.

**Comment by Lilzezzie** [comment]
yeah this problem sucks, i hope it gets fixed soon

**Comment by Lilzezzie** [comment]
> yeah this problem sucks, i hope it gets fixed soon

I too ran into this

**Comment by Average-FNF-Fan** [comment]
Mainly for me in the previous updates I've never had this problem except for a couple updates before.

**Comment by AsaTyr2018** [comment]
i use oobabooga as backend.

127.0.0.1 - - [08/May/2023 18:35:27] "POST /api/v1/generate HTTP/1.1" 200 -
127.0.0.1 - - [08/May/2023 18:35:29] "GET /api/v1/model HTTP/1.1" 200 -
127.0.0.1 - - [08/May/2023 18:35:32] "GET /api/v1/model HTTP/1.1" 200 -
127.0.0.1 - - [08/May/2023 18:35:35] "GET /api/v1/model HTTP/1.1" 200 -
Output generated in 10.16 seconds (4.82 tokens/s, 49 tokens, context 979, seed 1711662096)

So it genetate a respond but tavernAI don´t read it. hmmmm timeout issue? but 10 seconds? meh. i´m lost.

**Comment by Lilzezzie** [comment]
I think if you are using NovelAI then it will stop working if you run out of "credits" (u gotta pay for more space to write stories) on your NovelAI account, ig I would say use Kobold instead

**Comment by Average-FNF-Fan** [comment]
Update, the characters arent even talking anymore. they stopped responding, even when i create a new chat it doesnt work.

**Comment by AsaTyr2018** [comment]
> I think if you are using NovelAI then it will stop working if you run out of "credits" (u gotta pay for more space to write stories) on your NovelAI account, ig I would say use Kobold instead

i´m using a local Installation. so no credits required. ^^ "oobabooga"

**Comment by Borov666** [comment]
What error do you get in the console when the characters stop responding? It is advisable to get more information to understand what the problem is.

**Comment by AsaTyr2018** [comment]
no error. thats the problem. oobabooga just reicive the request, generate it and send it back to the TavernAI.
i made a cross check with SillyTavern. there it goes on and on and on. no stop. same configuration. it only happens with tavernAI.

**Comment by Average-FNF-Fan** [comment]
> What error do you get in the console when the characters stop responding? It is advisable to get more information to understand what the problem is.

When I keep talking to a character, it continues talking, but soon enough it stops responding. The little loading thingy stops and turns back into the feather with no response from the chatbot, i try reloading, deleting, and starting a new conversation but it always ends up no longer responding to me after 5 messages or more.

**Comment by Matinliukang** [comment]
exacly, someone pls answer how to fix

**Comment by Matinliukang** [comment]
> > What error do you get in the console when the characters stop responding? It is advisable to get more information to understand what the problem is.
> 
> When I keep talking to a character, it continues talking, but soon enough it stops responding. The little loading thingy stops and turns back into the feather with no response from the chatbot, i try reloading, deleting, and starting a new conversation but it always ends up no longer responding to me after 5 messages or more.

exacly

**Comment by CrownedLime747** [comment]
> > > What error do you get in the console when the characters stop responding? It is advisable to get more information to understand what the problem is.
> > 
> > 
> > When I keep talking to a character, it continues talking, but soon enough it stops responding. The little loading thingy stops and turns back into the feather with no response from the chatbot, i try reloading, deleting, and starting a new conversation but it always ends up no longer responding to me after 5 messages or more.
> 
> exacly

Same, also using colab
