### ISSUE TITLE
The openAI model did not respond to anything

### ISSUE THREAD

**Issue by ardst2** [TavernAI/TavernAI-v1#166]
The openAI model did not respond to anything. Yesterday was fine

What is the problem?

I'm running on free colab

**Comment by Borov666** [comment]
At the moment, this model has stopped accepting requests.

**Comment by ardst2** [comment]
Why?

**Comment by Borov666** [comment]
I do not know, but this has already happened before.

**Comment by ardst2** [comment]
So, just wait?

now the openAI model is gone

![GPU ipynb - Colaboratory](https://user-images.githubusercontent.com/132222900/236698309-3f85c76b-4d3d-4969-9311-c20b2457c57e.png)

**Comment by Borov666** [comment]
Apparently so.

**Comment by ardst2** [comment]
use your own API in your openAI account, but before that set up payment and "create a paid account" using a credit/debit card (NO CHARGE) and use GPT 3.5 in the settings menu in TavernAI UI.

If you subscribe to chatgpt plus I think you can use gpt4, but since I use a free openAI account I can't use gpt4.
