### ISSUE TITLE
Can't send or receive messages

### ISSUE THREAD

**Issue by bababor** [TavernAI/TavernAI-v1#167]
I'm new to these things and I have no clue on why is this happening but when I use the OpenAI API I can't send any messages to a bot.
KoboldAI API is not letting me connect but it may be because of the API key, problem is I don't know how to solve that issue.
Kobold Horde let's me send a message but it takes a long time before giving me an error.
It was working just fine yesterday early so I'm confused.

**Comment by ardst2** [comment]
me too

**Comment by SegoCode** [comment]
Check https://github.com/TavernAI/TavernAI/commit/ffd86ed89dae60afbca7dc13e312cd4df5d4385a and https://github.com/TavernAI/TavernAI/issues/166
