### ISSUE TITLE
Feature Request: Role Keyword Search and improve community functions

### ISSUE THREAD

**Issue by pp2020412** [TavernAI/TavernAI-v1#176]
We obviously have a labeling system now, but it's not enough. Every character uploaded online has their public panel content, such as first contact, character introduction, etc. By establishing a keyword search mechanism, users can find their favorite characters more quickly. In addition, I also suggest that users can follow each other to improve the community function. An excellent community can not only help users quickly find their favorite characters, solve the problem of character collection in disguise, but also inspire hard-working character creators. Come on, 4000 followers is cool! With the community as the foundation, subsequent value-added services can also be developed step by step.

**Comment by Borov666** [comment]
Yes, such functions are in the plans.
