### ISSUE TITLE
Stop Sequences?

### ISSUE THREAD

**Issue by VraethrDalkr** [TavernAI/TavernAI-v1#177]
I'm using koboldcpp api to connect with TavernAI. It would be nice if it could pass a stop_sequence string to the API, for example : [ '\nYou:' ] if my Avatar name was "You". That would prevent koboldcpp from generating a lot of extra text that is being dropped and speed up the chat quite significantly. Maybe there's already a way to do that, but I couldn't find anything. SillyTavern does it unless the selected preset is KoboldAI Settings. I'd rather use TavernAI because I prefer its UI. A customizable stop sequence would be perfect.

**Comment by ignamiranda** [comment]
I'd love this feature too because I'd set it to stop at line breaks to get overall shorter responses.

**Comment by aibosan** [comment]
In TAI (and Silly) you can use the singleline mode, which terminates generation when newline is reached. Not exactly the same, but it definitely saves generation time.
What's closer to what you're looking for is a proper integration of ChatMode in KAI, which would not break when used through the API. One of the features is that it's supposed to end generation at "\nYou: ", but formatting changes make it unusable.
