### ISSUE TITLE
Erebus 2.7B not availble in drop down menu in GPU Colab

### ISSUE THREAD

**Issue by Gerrytheskull** [TavernAI/TavernAI-v1#180]
Tried with koboldAI I tried to add it manually by typing its name in the drop menu but it handed me upon completion this error at the end:

 OSError: Erebus is not a local folder and is not a valid model identifier listed
on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to 
this repo with `use_auth_token` or log in with `huggingface-cli login` and pass 
`use_auth_token=True`.

**Comment by NizhamAhmadFatah** [comment]
i think you type it wrong, i tried to do it manually and it work fine for me

**Comment by sebastianelbasado** [comment]
Paste this and it will be done. - KoboldAI/OPT-2.7B-Erebus- (Dont copy the - )
