### ISSUE TITLE
World Info not working

### ISSUE THREAD

**Issue by ignamiranda** [TavernAI/TavernAI-v1#181]
This is a clean install of TavernAI.

![image](https://github.com/TavernAI/TavernAI/assets/34501347/06c7d933-5a95-4989-9607-7a5f7befab51)

**Comment by CaBPi** [comment]
World Info is also not working for me.
use_world_info: false,

**Comment by Borov666** [comment]
It looks like a world info problem with OpenAI only.

**Comment by Tadswat** [comment]
I don't think it works with NovelAI either. It certainly shows no indication in the powershell window or in generated replies.
