### ISSUE TITLE
To access the website, please confirm the tunnel creator's public IP below.

### ISSUE THREAD

**Issue by Danmat228** [TavernAI/TavernAI-v1#182]
![image](https://github.com/TavernAI/TavernAI/assets/133936846/4b0cad1d-e3a2-48b9-bd01-c83f932871d0)
what should I do?

**Comment by RandomArnab** [comment]
Same, i been stuck at it for an hour now, no clue.

**Comment by Otimkev** [comment]
Same, problem here too.

**Comment by Borov666** [comment]
The link with the required ip appears above the link with the tavern.

**Comment by Fabeca** [comment]
> The link with the required ip appears above the link with the tavern.

which link exactly ? all the ones I click one just go to the page where the ip is entered

**Comment by Borov666** [comment]
`which link exactly ? all the ones I click one just go to the page where the ip is entered`

When the notepad finishes loading, it gives a link to TavernAI, and above this link will be the ip that you need to enter.

**Comment by Fabeca** [comment]
odd, I see the link to tavernAI but no IP above it.

**Comment by Borov666** [comment]
![123](https://github.com/TavernAI/TavernAI/assets/121401040/6d25fc9f-1b9b-4cb5-97c1-01df5aecdffc)
It should be like this.

**Comment by Fabeca** [comment]
I get the link but no IP   
![tavernlink](https://github.com/TavernAI/TavernAI/assets/134233910/1fe75a70-d3af-44a0-bb25-b6ebe234a5c0)

**Comment by h4rldev** [comment]
Edit the code by pressing show code and add this:
```
print("############")
print("IP v")
!curl https://ipv4.icanhazip.com/
print("############")
```

before the `!wget koboldai`

Edit: this is if you're running localtunnel and using the TPU colab

**Comment by Borov666** [comment]
> I get the link but no IP

Do you use this Colab? https://colab.research.google.com/github/TavernAI/TavernAI/blob/main/colab/GPU.ipynb

**Comment by Fabeca** [comment]
> > I get the link but no IP
> 
> Do you use this Colab? https://colab.research.google.com/github/TavernAI/TavernAI/blob/main/colab/GPU.ipynb

This is the link I've been using https://colab.research.google.com/drive/1nArynBKAI3wqNXJcEOdq34mPzoKSS7EV?usp=share_link#scrollTo=hps3qtPLFNBb

**Comment by Borov666** [comment]
I do not know what this link is, so I can't say anything about the work of this notebook.

It is advisable to use the official TAI Colab.

**Comment by Fabeca** [comment]
> I do not know what this link is, so I can't say anything about the work of this notebook.
> 
> It is advisable to use the official TAI Colab.

yeah the official link worked for me.

**Comment by Aramatic** [comment]
https://youtu.be/zdJdJ1tHGnA you can watch video on YouTube. How to run streamlit using local tunnel after that it will ask for endpoint IP  to fix this issue you can watch video on YouTube. I have pasted the link where you can find the easiest way to fix your problem

**Comment by CarelleProfeta** [comment]
@Danmat228 

> ![image](https://user-images.githubusercontent.com/133936846/239125869-4b0cad1d-e3a2-48b9-bd01-c83f932871d0.png) what should I do?

I found a easier way to view your public IP

**1. Using Google:**
- Go to this link: https://www.whatismyip.com/ (this will view your public IP)

**2. Using cmd (Command Prompt):**
- Press the Windows key + R on your keyboard to open the Run dialog.
- Type "cmd" and press Enter to open the Command Prompt.
- In the Command Prompt window, type "nslookup myip.opendns.com resolver1.opendns.com" and press Enter.
- Look for the "Address" under the "Non-authoritative answer:" (Grab the IP provided and it in localtunnel friendly reminder)

_Disclaimer: This method works for me_ 😊

#HappyCoding

**Comment by h4rldev** [comment]
> @Danmat228 
> 
> > ![image](https://user-images.githubusercontent.com/133936846/239125869-4b0cad1d-e3a2-48b9-bd01-c83f932871d0.png) what should I do?
> 
> I found a easier way to view your public IP
> 
> **1. Using Google:**
> - Go to this link: https://www.whatismyip.com/ (this will view your public IP)
> 
> **2. Using cmd (Command Prompt):**
> - Press the Windows key + R on your keyboard to open the Run dialog.
> - Type "cmd" and press Enter to open the Command Prompt.
> - In the Command Prompt window, type "nslookup myip.opendns.com resolver1.opendns.com" and press Enter.
> - Look for the "Address" under the "Non-authoritative answer:" (Grab the IP provided and it in localtunnel friendly reminder)
> 
> _Disclaimer: This method works for me_ 😊
> 
> #HappyCoding
> 
> 

This is useless on colaboratory, but works if it's selfhosted, although idk why you would selfhost a colab

**Comment by Saksham1515** [comment]
> https://youtu.be/zdJdJ1tHGnA you can watch video on YouTube. How to run streamlit using local tunnel after that it will ask for endpoint IP  to fix this issue you can watch video on YouTube. I have pasted the link where you can find the easiest way to fix your problem 

thanks bro

**Comment by KiranHipparagi** [comment]
I have resolved the issue by doing  `!pip install streamlit --q`

**Comment by SarveshVGharat** [comment]
> https://youtu.be/zdJdJ1tHGnA you can watch video on YouTube. How to run streamlit using local tunnel after that it will ask for endpoint IP to fix this issue you can watch video on YouTube. I have pasted the link where you can find the easiest way to fix your problem

Thanks man, it worked
