### ISSUE TITLE
How to update TavernAI?

### ISSUE THREAD

**Issue by qazpllp** [TavernAI/TavernAI-v1#186]
What is the expected way to update TavernAI? I would expect such a question to be written clearly within the documentation. 
I tried updating with `git pull`. However, there is no `.gitignore`, and I need to handle all my changes, chats, e.t.c. Thus what is the way expected to update?

**Comment by Borov666** [comment]
As you said above, you can use "git pull" to update or download the source archive on the github page.

It was decided not to include gitignore in the repository, since each developer configures it for himself.
