### ISSUE TITLE
start-linux.sh is not executable

### ISSUE THREAD

**Issue by qazpllp** [TavernAI/TavernAI-v1#187]
The file `start-linux.sh` lacks executable permission in linux. I would expect the executable to be immediately executable, but it is not, due to lack of permission. This could be solved by ensuring git tracks this file with executable permission.

**Comment by AlpinDale** [comment]
I didn't know I could do that when I made the PR for the script, but hindsight is 20/20. I managed to do it properly with the [SillyTavern start script](https://github.com/Cohee1207/SillyTavern/blob/main/start.sh). Hopefully Humi fixes it on this repo as well.
