### ISSUE TITLE
Time out error

### ISSUE THREAD

**Issue by anto18671** [TavernAI/TavernAI-v1#188]
How can i increase the time before the time out error? I know my model work, but it just need a little bit more time to generate a response.

**Comment by 1275** [comment]
In Config.conf, change const connectionTimeoutMS = 2*60*1000 to X*60*1000 where X is the amount of minutes you would like

**Comment by Rivaidan** [comment]
> In Config.conf, change const connectionTimeoutMS = 2_60_1000 to X_60_1000 where X is the amount of minutes you would like

could you be a bit more specific? because all i see is `const connectionTimeoutMS = 5*60*1000; // The maximum duration of the request, after which TAI assumes the server will not reply at all (default is 2 minutes)` and no matter what i set those values too it still times out at 1minute.

**Comment by ThatSkepticalGamer** [comment]
I have the same problem, changing connectionTimeoutMS seems to not actually do anything. I left it at default, set it to 0, and set it to 2147483646, and they all timeout at the same time. An option to disable the Timeout would be a good option imo
