### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by jack-ramsey-jar** [TavernAI/TavernAI-v1#193]
When I run Start.bat normally, it closes after it finishes checking for vulnerabilities. I tried running it through Admin CMD, and I ended up getting an errno -4094. Why and how do I fix this?

![image](https://github.com/TavernAI/TavernAI/assets/122332317/cde3932d-9529-4ca9-89aa-9833da312dca)

**Comment by Borov666** [comment]
Try to set `autorun = false;` in config.conf
