### ISSUE TITLE
Open AI NSFW Jailbreak not working

### ISSUE THREAD

**Issue by Waryok** [TavernAI/TavernAI-v1#195]
Whenever i starting to do some nsfw action in versions past 1.3.0, bot giving me a message that it inappropriate.
![image](https://github.com/TavernAI/TavernAI/assets/126208266/a0d72927-3f52-45a0-a3a3-f74cf58f167c)
1.4.1 and 1.4.0 versions

![image](https://github.com/TavernAI/TavernAI/assets/126208266/b123201b-fa12-4ef3-bfb6-48e878dea0ac)
1.3.0, 1.3.1 versions

**Comment by moetc5** [comment]
you fix it?

**Comment by Waryok** [comment]
> you fix it?

Nope, still trying to find how
