### ISSUE TITLE
Timeout Error

### ISSUE THREAD

**Issue by miklask** [TavernAI/TavernAI-v1#196]
How can I increase the time before the time out error? In version 1.4.1 it already times out after 1 minute and it ignores whatever I input into the config.conf.

**Comment by Borov666** [comment]
Which API is this for?

**Comment by miklask** [comment]
I use oobabooga on windows and would like to use my 30B models, but they always time out. On tavern Ai I use the KoboldAI preset.
I did not have this problem in Tavern ai 1.3 and 1.4. And exe and bat have the same issue.

**Comment by miklask** [comment]
OK I solved it with changing Line 377 in script.js to    requestTimeout = data.timeout;
I have no idea what I am doing, and I just tried some stuff, but it seems the new setTimeout stuff does not work, and I tried to get close to the previous solution. I leave this issue open for the moment to make sure the people who need to see it, see it. 
But for my case it is working with this fix

**Comment by Borov666** [comment]
Fix has been added in repo https://github.com/TavernAI/TavernAI/commit/c83cc68a105e3ed9cb25a0fa9bc27ceb90a610a4
