### ISSUE TITLE
Open.AI Connection Issue

### ISSUE THREAD

**Issue by Y0KA1-1** [TavernAI/TavernAI-v1#197]
Whenever I use an Open.AI model, no matter which one it is, it will give me a connection, but whenever I send any message to any character, it generates for a second, and then stops. I've tried it again, I've reran the Colab, I've reloaded the page, I've done other APIs, and I've checked my memory. Everything else works fine, but I've had a lot of issues using the Open.AI's connection. I'm not sure if it's my memory or not, because sometimes it'll let me send one message to the character, and then after that it just stops generating responses. I use GPT 3.5 Turbo primarily since I cannot afford GPT 4, but even GPT 3.5 Turbo won't generate a response.

**Comment by aguywithoutalife** [comment]
yea man, this happens to me too,  for some reason yesterday that happened, idk why tho since, before it worked for me well.
