### ISSUE TITLE
Collab Doc not working

### ISSUE THREAD

**Issue by casualbread** [TavernAI/TavernAI-v1#199]
When clicking the link it says you need an end point IP, was wondering if anybody knows it.

**Comment by Borov666** [comment]
It is written above the link with TavernAI

**Comment by crux-03** [comment]
Can confirm, it does not seem to work with the KoboldAI API. Even with Colab Pro's premium hardware.
![image](https://github.com/TavernAI/TavernAI/assets/25249091/9d52d1cf-f563-4446-8c39-743fc0b20a47)

**Comment by casualbread** [comment]
> 

> It is written above the link with TavernAI

Thank you
