### ISSUE TITLE
OpenAI wont respond.

### ISSUE THREAD

**Issue by aguywithoutalife** [TavernAI/TavernAI-v1#200]
So a couple days ago, I decided to open tavernAI, it worked in the past so yeah, but when I messaged the AI it wouldn't respond. Yes I've tried getting a new API and resetting the connection and the colab to refresh l but nothin' worked. And If I do Koboloid AI, It'll just respond to me with 1 sentence short text, and most of the time it doesn't even work!.

Can Somebody Help Me?

**Comment by Borov666** [comment]
What error/response do you get in console?

**Comment by aguywithoutalife** [comment]
> What error/response do you get in console?

idk, i didnt see the colab, when I open colab tho, it had no error, but for the actual tavern ai, nothin worked for tavern AI
do you think it might have been because of free trial running out? or idk? cause i remember than making an OPENAI account was free

**Comment by aguywithoutalife** [comment]
I also tried on another alt account(brand new) and made a new OPEN AI account and APi, it was set on 3.5 turbo and it still wont respond bruh

**Comment by Borov666** [comment]
It's hard to say here, for example, sometimes the model are overloaded or the message limit per minute is exhausted and therefore no response comes.

**Comment by moetc5** [comment]
Yes, the same thing happened to me a few days ago, no matter how many things I do, chatgpt still doesn't respond

**Comment by aguywithoutalife** [comment]
> It's hard to say here, for example, sometimes the model are overloaded or the message limit per minute is exhausted and therefore no response comes.



> Yes, the same thing happened to me a few days ago, no matter how many things I do, chatgpt still doesn't respond


I found why: so basically, my trial or yours has ran out from the quota of the OPENAI API, either you have to make a new account or you use another alternative.

**Comment by moetc5** [comment]
> > It's hard to say here, for example, sometimes the model are overloaded or the message limit per minute is exhausted and therefore no response comes.
> 
> > Yes, the same thing happened to me a few days ago, no matter how many things I do, chatgpt still doesn't respond
> 
> I found why: so basically, my trial or yours has ran out from the quota of the OPENAI API, either you have to make a new account or you use another alternative.

Yes, I also realized that my API reached the limit, but to create a new account I need a new cell phone number, right?

**Comment by aguywithoutalife** [comment]
> > > It's hard to say here, for example, sometimes the model are overloaded or the message limit per minute is exhausted and therefore no response comes.
> > 
> > 
> > > Yes, the same thing happened to me a few days ago, no matter how many things I do, chatgpt still doesn't respond
> > 
> > 
> > I found why: so basically, my trial or yours has ran out from the quota of the OPENAI API, either you have to make a new account or you use another alternative.
> 
> Yes, I also realized that my API reached the limit, but to create a new account I need a new cell phone number, right?

sorry for the long response, had some exams..Anyway, yea i think you gotta get new number(or the same phone number, only 2 accounts you can used your same phone number on i think) and account.

**Comment by moetc5** [comment]
Hi, I've been busy with final exams too haha, but I used my number in another account, but apparently the free API is only once per number. Create a new account with another number and I have already had functional API again, so the solution is to create a new account with another cell phone number

**Comment by aguywithoutalife** [comment]
> Hi, I've been busy with final exams too haha, but I used my number in another account, but apparently the free API is only once per number. Create a new account with another number and I have already had functional API again, so the solution is to create a new account with another cell phone number

Oh, lol. Yeah though, it kinda sucks cause you cant make a new account on Open AI without doing tedious tasks(I'm to lazy to do it and it sounds annoying as hell) lmao.

**Comment by aguywithoutalife** [comment]
do you guys also know a solution with really short Kobold AI responses? just askin.

**Comment by aguywithoutalife** [comment]
also, when will you think the Tavern AI website(actually) will come out?(since its in working i think)
