### ISSUE TITLE
Kobold AI has short responses

### ISSUE THREAD

**Issue by aguywithoutalife** [TavernAI/TavernAI-v1#201]
As you can read from the title, everytime I select Kobold AI, it always responds with short-term responses.

example-

Me: "blah blah blah blah?" *insert action*

AI: "blah blah"

So it basically only responds with the words(which are pretty short), and no action at all, and sometimes it wont even respond back lol.

(google colab version)

**Comment by LoonyBeLuna** [comment]
I had the same experience and stopped using TavernAi because of that and did went back to CharAI, even if I have to play around the filter, the TavernAI makes no fun...
But... I think this is nothing that the TavernAI Team can change, this is a problem with the "models".

**Comment by aguywithoutalife** [comment]
> I had the same experience and stopped using TavernAi because of that and did went back to CharAI, even if I have to play around the filter, the TavernAI makes no fun... But... I think this is nothing that the TavernAI Team can change, this is a problem with the "models".

ah, i see, thanks for answering and sorry for the long response, i had to do some things lmao

**Comment by LoonyBeLuna** [comment]
> 

No problem ;)

**Comment by Borov666** [comment]
TavernAI is only an interface and we do not develop AI models. For KoboldAI models, the "Anchors" system was created to increase the length of messages for classic KoboldAI models. It can be enabled in the settings of TavernAI. For longer messages and more logical responses, it is advisable to use the OpenAI API or Reverse Proxy with Anthropic models.

**Comment by aguywithoutalife** [comment]
> TavernAI is only an interface and we do not develop AI models. For KoboldAI models, the "Anchors" system was created to increase the length of messages for classic KoboldAI models. It can be enabled in the settings of TavernAI. For longer messages and more logical responses, it is advisable to use the OpenAI API or Reverse Proxy with Anthropic models.

sorry to ask a week later, how do I do all of that(dont link or explain OPENAI cause I've run out of the thing) like the reverse proxy or something, can you link something or explain? Thanks.

**Comment by Borov666** [comment]
> sorry to ask a week later, how do I do all of that(dont link or explain OPENAI cause I've run out of the thing) like the reverse proxy or something, can you link something or explain? Thanks.

Reverse Proxies are typically private servers that provide access to language models or act as intermediaries for accessing corporate models. Some of them require a password for access. When using Reverse Proxies, it is important to consider the weak confidentiality of this method.
