### ISSUE TITLE
Unable to send text in message box

### ISSUE THREAD

**Issue by emmalexandria** [TavernAI/TavernAI-v1#206]
I can select the model (using horde currently, but had same issue with a local model) and type a message, but when I press enter/click the send button for the first time this error outputs in the browser console:

```
Uncaught (in promise) TypeError: Characters.id[Characters.selectedID] is undefined
    Generate http://127.0.0.1:8000/script.js:1182
    <anonymous> http://127.0.0.1:8000/script.js:2348
    jQuery 2
script.js:1182:9
    Generate http://127.0.0.1:8000/script.js:1910
    <anonymous> http://127.0.0.1:8000/script.js:2348
    jQuery 2
```

and nothing is sent

**Comment by redfish64** [comment]
I ran into this, too. As a workaround, go to the character menu in the upper right and choose a character on first load before typing anything.

**Comment by Borov666** [comment]
Fixed in https://github.com/TavernAI/TavernAI/commit/78715b03181b22626cbc1bd4fa9a388d2c7d3343
