### ISSUE TITLE
No responses from any character

### ISSUE THREAD

**Issue by BojanIlie** [TavernAI/TavernAI-v1#208]
I tried to use both web and app version, with OpenAi, but the characters don't respond to any kind of text I write.
I tried to delete and make a new key but it still doesn't work, any ideas? (The key connects but I still get no responses.)

**Comment by Borov666** [comment]
What error do you get in console?

**Comment by moetc5** [comment]
Have you checked your API usage yet? The same thing happened to me and the reason was that I no longer had a free trial in the API
