### ISSUE TITLE
Feature Request: Add support for World Info

### ISSUE THREAD

**Issue by TarotFooling** [TavernAI/TavernAI-v1#21]
Kobold Supports World Info, and to be the first Pygmalion friendly UI to support World Info would be a massive boon. From what I've seen of a custom implementation of World Info with a conversational model, it can work wonders! Especially for people who like crafting detailed characters with lots of info.

This can be more of a long term thing, but I'd love to see it added one day.

**Comment by Borov666** [comment]
World Info support was added in 1.4.0
