### ISSUE TITLE
Feature Request: Support higher context sizes

### ISSUE THREAD

**Issue by Ontanio** [TavernAI/TavernAI-v1#213]
With the new ExLlama model loader and 8K models we can have context sizes up to 8192. TavernAI is currently hard locked to 2048. Could you please add the support for the higher context sizes for these new models when using KoboldAI API (via oobabooga)? This would be extremly valuable for everything role play (more detailed characers and environments as well as better memory of past events).

**Comment by Borov666** [comment]
The context for KoboldAI has been enlarged and the possibility of manual input has been added https://github.com/TavernAI/TavernAI/commit/00b81758f088399c31e1fc7a7e1a1c87925d2c4e
