### ISSUE TITLE
No connection to charaCloud

### ISSUE THREAD

**Issue by LazerCuber** [TavernAI/TavernAI-v1#214]
Is there a issue with the databse?

**Comment by CanadainMunchkin** [comment]
characloud might no longer be a part of it its been down for hours and discord they have not posted anything. but time will tell lol

**Comment by CanadainMunchkin** [comment]
https://tavernai.net/ is down that is why its not working so until they fix https://tavernai.net/ there will be no Characloud there site is up and running so its on tavern's side

**Comment by LazerCuber** [comment]
I wonder why the devs didn't address this issue

**Comment by CanadainMunchkin** [comment]
one it could be characloud or maybe now its only for paid subscribers depending on what monthly package you buy. then again its just a guess but it would make sense no one even addressed this issue. to me that is most logical.

**Comment by TavernAI** [comment]
There were technical works on the server. Now it's online again.
