### ISSUE TITLE
Character library is not showing

### ISSUE THREAD

**Issue by yujiechiu** [TavernAI/TavernAI-v1#215]
Hi, I am new to this community, so if I asked some dumb questions, I am truly sorry! But I really need help.

At first, I am following this guide to start, but it turns out there's nothing when I opened Character library (picture below).
[https://home.gamer.com.tw/artwork.php?sn=5698780](url)

![Tavern AI - Google Chrome 2023_7_21 下午 04_22_34](https://github.com/TavernAI/TavernAI/assets/140151715/8a3ddccb-1874-4434-bbdf-7f40efdfd0d8)

Then I've tried following the guide to fix this problem, but it didn't work.
[https://github.com/TavernAI/TavernAI/wiki/How-to-install](url)

What should I do to fix this problem QQ

**Comment by LazerCuber** [comment]
Hi yujiechiu, charaCloud (cloud server for the character library) is down so all users are also affected(I think), the only solution now is go to [characterhub](https://www.characterhub.org) and download the character you want (or you have your own character already created) and chat.

Just wait until characloud is back 😅 

_for the record characloud being down does not affect your ability to use tavern. It simply means you can't download new chars from characloud.  All your existing chars are still there._ - from the tavern discord admin

**Comment by TavernAI** [comment]
There were technical works on the server. Now it's online again.

**Comment by yujiechiu** [comment]
Thank you !!!!
