### ISSUE TITLE
Master settings not saved + console/terminal not showing anything

### ISSUE THREAD

**Issue by LazerCuber** [TavernAI/TavernAI-v1#218]
After I updated to Tavern 1.5, it seems that I can't save my master settings after reloading and terminal doesn't show anything. But when I go to the settings in the file it shows the changes?

**Comment by Borov666** [comment]
Can you describe the problem in more detail so that it can be reproduced? Which version of the tavern are you using (node or exe)? Which settings exactly are you changing?

**Comment by LazerCuber** [comment]
I'm using node and I'm trying to change the model settings and I want to turn swipes, auto connect and memory scroll on but after I reload the page, those reverted back to default.

Another issue: Terminal/console doesn't show any activity when I try to chat with characters

**Comment by Borov666** [comment]
It looks like something has happened to your currently installed version. Try installing the new installation in a new folder.

**Comment by LazerCuber** [comment]
New folder?
