### ISSUE TITLE
Feature Request: Swapping <USER> with user name in character files

### ISSUE THREAD

**Issue by rsmyst** [TavernAI/TavernAI-v1#22]
Can this be done locally on tavern when sending inputs for generation instead of on pygmalion's side?
it would make sharing character a whole lot easier if i could just write <USER> in place of my username or You. tavernAI could just swap out <USER> with username of the person using tavern. 

otherwise, people are running into issues where if they forget to change my username to theirs in a character card, the AI treats my username as a separate character who is a friend instead of being the character the bot is supposed to be talking to.

**Comment by rsmyst** [comment]
would like to add that pygmalion itself supports <USER>, tavern just has to replace it on the UI with username

**Comment by Borov666** [comment]
Currently, {{user}} and {{char}} are being replaced in the dialog examples

**Comment by rsmyst** [comment]
> Currently, {{user}} and {{char}} are being replaced in the dialog examples

would be nice to use it in greetings itself + in desc.

**Comment by TavernAI** [comment]
Added in 1.2.7
