### ISSUE TITLE
Feature Request: Support for the new NovelAI model Kayra

### ISSUE THREAD

**Issue by Tadswat** [TavernAI/TavernAI-v1#222]
Kayra, the new 13B model is out. I can't wait for support for this in TavernAI, I know when Clio was launched you guys were super fast getting support out so we are all hoping for the same again.

**Comment by TavernAI** [comment]
This has already been added https://github.com/TavernAI/TavernAI/commit/f9e971645810dbd7314cacd4023cbe2e9de8424f

**Comment by Tadswat** [comment]
Great, thanks. I have added the Kayra option now in the NovelAI Settings folder and it now shows up on the Preset Settings drop down list in the Tavern UI, so that's fine.
I updated the script.js exactly as shown so that's good
Lastly I updated the index.html but this will not update in the Tavern UI and show Kayra as an option in the Models dropdown. I have deleted my chrome cache etc, even and it still won't let me select (or even show) Kayra. 
Anything I can do to make it work? or do I have to wait for the next release.

**Comment by Borov666** [comment]
If you have git, you just can make "git pull".

The release will be in the next two days.

**Comment by Tadswat** [comment]
I don't have git, sadly. But I can wait two days, that is fantastic. Thanks Borov :)

**Comment by Borov666** [comment]
https://github.com/TavernAI/TavernAI/archive/refs/heads/main.zip You also can run this, github automatically collects the latest version from new comits

**Comment by Tadswat** [comment]
You sir are a star, thank you so much :)
