### ISSUE TITLE
TavernAI Crashing on any message

### ISSUE THREAD

**Issue by AsaTyr2018** [TavernAI/TavernAI-v1#231]
Hey there.
my TavernAI crashes instantly once i type a message. Regardless its Lengh.

I Use Text Generation WebUI (Oobabooga) in latest Git Revision. And TavernAI 1.5.1 (Git Cloned just 10 Minutes ago)
Model: elinas_chronos-13b-4bit [https://huggingface.co/elinas/chronos-13b-4bit](url)

This is the console Output on crash:

PS F:\Text-Ai-Adds\TavernAI--1.5.1> .\Start.bat

F:\Text-Ai-Adds\TavernAI--1.5.1>call npm install

up to date, audited 110 packages in 877ms

30 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
F:\Text-Ai-Adds\TavernAI--1.5.1\server.js:5
const open = require('open');
             ^

Error [ERR_REQUIRE_ESM]: require() of ES Module F:\Text-Ai-Adds\TavernAI--1.5.1\node_modules\open\index.js from F:\Text-Ai-Adds\TavernAI--1.5.1\server.js not supported.
Instead change the require of index.js in F:\Text-Ai-Adds\TavernAI--1.5.1\server.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (F:\Text-Ai-Adds\TavernAI--1.5.1\server.js:5:14) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.16.0

Additional Info:
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] on win32
Windows 11 Enterprise 22H2 Bulld 22621.2283

pip list:
Package                                  Version
---------------------------------------- -----------
abstract_singleton                       1.0.1
agbenchmark                              0.0.2
agent-protocol                           0.1.1
aiofiles                                 23.1.0
aiohttp                                  3.8.4
aiosignal                                1.3.1
alembic                                  1.12.0
altair                                   5.0.1
antlr4-python3-runtime                   4.9.3
anyio                                    3.6.2
apache-airflow                           2.7.1
apache-airflow-providers-common-sql      1.7.2
apache-airflow-providers-ftp             3.5.2
apache-airflow-providers-http            4.5.2
apache-airflow-providers-imap            3.3.2
apache-airflow-providers-sqlite          3.4.3
apispec                                  6.3.0
argcomplete                              3.1.1
argilla                                  1.7.0
args                                     0.1.0
asgiref                                  3.7.2
astroid                                  2.3.3
async-timeout                            4.0.2
asynctest                                0.13.0
attrs                                    23.1.0
auto_gpt_plugin_template                 0.0.2
autoflake                                2.2.0
Babel                                    2.12.1
backoff                                  2.2.1
beautifulsoup4                           4.12.2
bidict                                   0.22.1
bitmath                                  1.3.3.1
black                                    23.7.0
blinker                                  1.6.2
blis                                     0.7.10
boto3                                    1.28.7
botocore                                 1.31.7
Brotli                                   1.0.9
bs4                                      0.0.1
cachelib                                 0.9.0
cachetools                               5.3.1
catalogue                                2.0.9
cattrs                                   23.1.2
certifi                                  2023.5.7
cffi                                     1.15.1
cfgv                                     3.3.1
chardet                                  4.0.0
charset-normalizer                       3.2.0
chromadb                                 0.3.23
click                                    8.1.3
clickclick                               20.10.2
clickhouse-connect                       0.5.24
clint                                    0.5.1
cloudscraper                             1.2.71
cmake                                    3.27.2
colorama                                 0.4.6
colorclass                               2.2.2
coloredlogs                              15.0.1
colorlog                                 4.8.0
commonmark                               0.9.1
compressed-rtf                           1.0.6
confection                               0.1.0
ConfigUpdater                            3.1.1
connexion                                2.14.2
contourpy                                1.1.0
controlnet-aux                           0.0.3
coverage                                 7.2.7
cron-descriptor                          1.4.0
croniter                                 1.4.1
cryptography                             40.0.2
cssselect                                1.2.0
cycler                                   0.11.0
cymem                                    2.0.7
dacite                                   1.7.0
dataclasses-json                         0.5.7
Deprecated                               1.2.13
deprecation                              2.1.0
dghs-imgutils                            0.2.6
diffusers                                0.16.1
dill                                     0.3.6
distlib                                  0.3.7
distro                                   1.8.0
dnspython                                2.4.0
docker                                   6.1.3
docutils                                 0.20.1
duckdb                                   0.8.0
duckduckgo-search                        3.0.2
easygui                                  0.98.3
ebcdic                                   1.1.1
einops                                   0.6.1
email-validator                          1.3.1
emoji                                    2.8.0
en-core-web-sm                           3.5.0
et-xmlfile                               1.1.0
eventlet                                 0.33.3
exceptiongroup                           1.1.2
execnet                                  2.0.2
extract-msg                              0.41.1
fairscale                                0.4.13
fastapi                                  0.100.1
ffmpy                                    0.3.0
fiftyone                                 0.21.4
fiftyone-brain                           0.13.0
fiftyone-db                              0.4.0
fiftyone-desktop                         0.28.2
filelock                                 3.12.2
flake8                                   6.1.0
Flask                                    2.2.3
Flask-AppBuilder                         4.3.6
Flask-Babel                              2.0.0
Flask-Caching                            2.0.2
Flask-Cors                               4.0.0
Flask-JWT-Extended                       4.5.2
Flask-Limiter                            3.5.0
Flask-Login                              0.6.2
Flask-Session                            0.5.0
Flask-SocketIO                           5.3.5
Flask-SQLAlchemy                         2.5.1
Flask-WTF                                1.1.1
flaskwebgui                              0.3.5
flatbuffers                              23.5.26
fonttools                                4.41.0
frozenlist                               1.3.3
fsspec                                   2023.5.0
ftfy                                     6.1.1
future                                   0.18.3
future-fstrings                          1.2.0
ghp-import                               2.1.0
gitdb                                    4.0.10
GitPython                                3.1.31
glfw                                     2.6.1
glob2                                    0.7
google-api-core                          2.11.1
google-api-python-client                 2.95.0
google-auth                              2.22.0
google-auth-httplib2                     0.1.0
google-re2                               1.1
googleapis-common-protos                 1.60.0
gradio                                   3.39.0
gradio_client                            0.3.0
graphql-core                             3.2.3
graphviz                                 0.20.1
greenlet                                 2.0.2
grpcio                                   1.58.0
gTTS                                     2.3.1
gunicorn                                 21.2.0
h11                                      0.14.0
h2                                       4.1.0
hbutils                                  0.9.1
hf_transfer                              0.1.3
hnswlib                                  0.7.0
hpack                                    4.0.0
html5lib                                 1.1
httpcore                                 0.17.3
httplib2                                 0.22.0
httptools                                0.5.0
httpx                                    0.24.1
huggingface-hub                          0.14.1
humanfriendly                            10.0
hypercorn                                0.14.4
hyperframe                               6.0.1
identify                                 2.5.26
idna                                     2.8
imageio                                  2.31.1
imageio-ffmpeg                           0.4.8
IMAPClient                               2.3.1
img2texture                              1.0.6
imgui                                    2.0.0
importlib-metadata                       6.8.0
importlib-resources                      6.1.0
inflate64                                0.3.1
inflection                               0.5.1
iniconfig                                2.0.0
inquirerpy                               0.3.4
isort                                    5.12.0
itsdangerous                             2.1.2
Jinja2                                   3.1.2
jmespath                                 1.0.1
joblib                                   1.2.0
jsonlines                                3.1.0
jsonschema                               4.18.4
jsonschema-specifications                2023.7.1
kaleido                                  0.2.1
kiwisolver                               1.4.4
lama-cleaner                             1.2.3
langchain                                0.0.171
langcodes                                3.3.0
lark-parser                              0.12.0
lazy_loader                              0.3
lazy-object-proxy                        1.4.3
limits                                   3.6.0
linkify-it-py                            2.0.2
llama-cpp-python                         0.1.50
llvmlite                                 0.40.1
lockfile                                 0.12.2
loguru                                   0.7.0
lxml                                     4.9.2
lz4                                      4.3.2
Mako                                     1.2.4
Markdown                                 3.4.3
markdown-it-py                           2.2.0
MarkupSafe                               2.1.2
marshmallow                              3.19.0
marshmallow-enum                         1.5.1
marshmallow-oneofschema                  3.0.1
marshmallow-sqlalchemy                   0.26.1
matplotlib                               3.7.2
mccabe                                   0.7.0
mdit-py-plugins                          0.3.3
mdurl                                    0.1.2
mergedeep                                1.3.4
mkdocs                                   1.5.1
mongoengine                              0.24.2
monotonic                                1.6
motor                                    3.2.0
mpmath                                   1.3.0
msg-parser                               1.2.0
msoffcrypto-tool                         5.0.1
multidict                                6.0.4
multivolumefile                          0.2.3
murmurhash                               1.0.9
mypy                                     1.4.1
mypy-extensions                          1.0.0
networkx                                 3.1
neuralgym                                0.0.1
ninja                                    1.10.2
nltk                                     3.8.1
nodeenv                                  1.8.0
numba                                    0.57.1
numexpr                                  2.8.4
numpy                                    1.23.5
olefile                                  0.46
oletools                                 0.60.1
omegaconf                                2.3.0
onnxruntime                              1.15.1
openai                                   0.27.8
openapi-python-client                    0.13.4
openapi-schema-pydantic                  1.2.4
opencv-python                            4.8.0.76
opencv-python-headless                   4.8.0.74
openpyxl                                 3.1.2
opentelemetry-api                        1.20.0
opentelemetry-exporter-otlp              1.20.0
opentelemetry-exporter-otlp-proto-common 1.20.0
opentelemetry-exporter-otlp-proto-grpc   1.20.0
opentelemetry-exporter-otlp-proto-http   1.20.0
opentelemetry-proto                      1.20.0
opentelemetry-sdk                        1.20.0
opentelemetry-semantic-conventions       0.41b0
ordered-set                              4.1.0
orjson                                   3.8.10
outcome                                  1.2.0
packaging                                23.1
pandas                                   1.5.3
pandoc                                   2.3
pathspec                                 0.11.2
pathy                                    0.10.2
pcodedmp                                 1.2.6
pdfminer.six                             20221105
pendulum                                 2.1.2
pexpect                                  4.8.0
pfzy                                     0.3.4
piexif                                   1.1.3
pilgram                                  1.2.1
Pillow                                   10.0.1
pilmoji                                  2.0.4
pinecone-client                          2.2.1
pip                                      23.2.1
pixivpy3                                 3.7.3
platformdirs                             3.10.0
playsound                                1.2.2
plotly                                   5.15.0
pluggy                                   1.2.0
plumbum                                  1.8.1
ply                                      3.11
pooch                                    1.7.0
posthog                                  3.0.1
pprintpp                                 0.4.0
pre-commit                               3.3.3
preshed                                  3.0.8
priority                                 2.0.0
prison                                   0.2.1
prompt-toolkit                           3.0.39
protobuf                                 4.23.4
psutil                                   5.9.5
ptyprocess                               0.7.0
py-cpuinfo                               9.0.0
py7zr                                    0.20.5
pyasn1                                   0.5.0
pyasn1-modules                           0.3.0
pybcj                                    1.0.1
pycodestyle                              2.11.0
pycparser                                2.21
pycryptodomex                            3.18.0
pydantic                                 1.10.12
pydub                                    0.25.1
pyflakes                                 3.1.0
Pygments                                 2.15.1
pygpt4all                                1.1.0
pygptj                                   2.0.3
PyJWT                                    2.8.0
pylatexenc                               2.10
pylint                                   2.4.4
pyllamacpp                               2.3.0
PyMatting                                1.1.8
pymdown-extensions                       10.1
pymongo                                  4.4.1
PyOpenGL                                 3.1.7
pyOpenSSL                                23.2.0
pypandoc                                 1.11
pyparsing                                2.4.7
PyPDF2                                   3.0.1
pyppmd                                   1.0.0
pyquery                                  2.0.0
pyreadline3                              3.4.1
PySocks                                  1.7.1
pytest                                   7.4.0
pytest-asyncio                           0.21.1
pytest-benchmark                         4.0.0
pytest-cov                               4.1.0
pytest-depends                           1.0.1
pytest-integration                       0.2.3
pytest-mock                              3.11.1
pytest-recording                         0.13.0
pytest-xdist                             3.3.1
python-daemon                            3.0.1
python-dateutil                          2.8.2
python-docx                              0.8.11
python-dotenv                            0.21.0
python-engineio                          4.6.1
python-magic                             0.4.27
python-multipart                         0.0.6
python-nvd3                              0.15.0
python-pptx                              0.6.21
python-slugify                           8.0.1
python-socketio                          5.8.0
pytimeparse                              1.1.8
pytz                                     2023.3
pytz-deprecation-shim                    0.1.0.post0
pytzdata                                 2020.1
PyWavelets                               1.4.1
pywin32                                  306
PyYAML                                   6.0
pyyaml_env_tag                           0.1
pyzstd                                   0.15.9
rarfile                                  4.0
readability-lxml                         0.8.1
red-black-tree-mod                       1.20
redis                                    4.6.0
referencing                              0.30.0
regex                                    2023.5.5
rembg                                    2.0.50
requests                                 2.31.0
requests-toolbelt                        1.0.0
retrying                                 1.3.4
rfc3339-validator                        0.1.4
rfc3986                                  1.5.0
rich                                     13.0.1
rich-argparse                            1.3.0
rpds-py                                  0.9.2
rsa                                      4.9
RTFDE                                    0.0.2
s3transfer                               0.6.1
safetensors                              0.3.2
scikit-image                             0.20.0
scikit-learn                             1.2.2
scipy                                    1.11.0
selenium                                 4.1.4
semantic-version                         2.10.0
sentence-transformers                    2.2.2
sentencepiece                            0.1.99
setproctitle                             1.3.2
setuptools                               65.5.0
shellingham                              1.5.0.post1
simple-websocket                         0.10.1
six                                      1.13.0
smart-open                               6.3.0
smmap                                    5.0.0
sniffio                                  1.3.0
sortedcontainers                         2.4.0
soupsieve                                1.9.5
spacy                                    3.5.4
spacy-legacy                             3.0.12
spacy-loggers                            1.0.4
SQLAlchemy                               1.4.49
SQLAlchemy-JSONField                     1.0.1.post0
SQLAlchemy-Utils                         0.41.1
sqlparse                                 0.4.4
srsly                                    2.4.7
sse-starlette                            0.10.3
sseclient-py                             1.7.2
starlette                                0.27.0
strawberry-graphql                       0.138.1
subprocess.run                           0.0.8
sympy                                    1.12
tabulate                                 0.9.0
tenacity                                 8.2.2
termcolor                                2.3.0
text-unidecode                           1.3
texttable                                1.6.7
thinc                                    8.1.10
threadpoolctl                            3.1.0
tifffile                                 2023.7.18
tiktoken                                 0.3.3
timm                                     0.9.5
tokenizers                               0.13.3
tomli                                    2.0.1
toolz                                    0.12.0
torch                                    2.0.1
torchvision                              0.15.2
tqdm                                     4.65.0
transformers                             4.27.4
trio                                     0.22.2
trio-websocket                           0.10.3
typer                                    0.7.0
types-beautifulsoup4                     4.12.0.5
types-colorama                           0.4.15.12
types-html5lib                           1.1.11.15
types-Markdown                           3.4.2.10
types-Pillow                             10.0.0.2
types-requests                           2.31.0.2
types-urllib3                            1.26.25.14
typing_extensions                        4.5.0
typing-inspect                           0.8.0
tzdata                                   2023.3
tzlocal                                  4.2
uc-micro-py                              1.0.2
unicodecsv                               0.14.1
universal-analytics-python3              1.1.1
unrpa                                    2.3.0
unstructured                             0.6.6
uritemplate                              4.1.1
urllib3                                  2.0.5
urllib3-secure-extra                     0.1.0
uvicorn                                  0.22.0
vcrpy                                    4.2.1
virtualenv                               20.24.2
voxel51-eta                              0.10.0
waifuc                                   0.0.1
wasabi                                   1.1.2
watchdog                                 3.0.0
watchfiles                               0.19.0
wcwidth                                  0.2.6
webdriver-manager                        4.0.0
webencodings                             0.5.1
websocket-client                         1.6.1
websockets                               11.0.3
Werkzeug                                 2.2.3
whichcraft                               0.6.1
win-unicode-console                      0.5
win32-setctime                           1.1.0
wrapt                                    1.14.1
wsproto                                  1.2.0
WTForms                                  3.0.1
XlsxWriter                               3.1.1
xmltodict                                0.13.0
yacs                                     0.1.8
yarl                                     1.9.2
zipp                                     3.16.2
zstandard                                0.21.0

**Comment by FunkEngine2023** [comment]
![image](https://github.com/TavernAI/TavernAI/assets/123712145/b4c5b458-7bde-4023-bd21-498c95eccaa9)
Requires node 19 and up. Use current not LTS.
