### ISSUE TITLE
`/getstatus` get called every 3 seconds ?

### ISSUE THREAD

**Issue by ilyaSuperGlue** [TavernAI/TavernAI-v1#233]
![image](https://github.com/TavernAI/TavernAI/assets/36694324/78d3840d-5e68-4f66-a3ee-338cdf29a748)

**Comment by Borov666** [comment]
Yes, it pings server.

**Comment by ilyaSuperGlue** [comment]
> Yes, it pings server.

Does heartbeat really necessary? 
Because if i look at the code it's use rest api for generation and stuff ? Cmiiw
