### ISSUE TITLE
Repeated Generic Error or Server Busy error with Kobold AI

### ISSUE THREAD

**Issue by Waifuwars69** [TavernAI/TavernAI-v1#238]
I'm running tavern AI and KoboldAI in parallel for local usage, but I've been repeatedly getting an error with TavernAI WebUI saying either just "error" or "server is busy". Ive been using KoboldCPP for local hosting, and i've tested this on both a machine with an NVidia GPU using CuBlas + CPU and on a higher end machine with an AMD card using CuBlast + CPU and get the same problem on both.  When it errors out, the TavernAI command line doesn't show any failure, and still receives the generated response from kobold as shown in screenshots below. When it DOES get the "Server is busy" error in the WebUI, it reflects as such in the command line but still receives the response from Kobold.

I've tried using varying ranges of GPU offloading in kobold on varying context sizes ranging from 1024 to 16668 (both in KoboldCPP and in tavernAI WebUI for settings) and get the same results, as well as adjusting how many core threads it uses too and even get it on 6 thread usage where a 100 token response takes under 30 seconds between my CPU and GPU. It happens on characters with barely any details and those with extended chat history/details too. It errors out far before it hits the timeout of 5 minutes in the config.config file. I've tried adjusting that to 20 as well just to rule it out and no dice. It shouldn't be hitting a timeout anyway as it's going over the local Loopback address since i'm hosting them both locally. It doesn't seem to happen when I have the response token amount to 80 or below, but anything above that seems to trigger this with a reasonable consistency. I've also monitored my CPU/RAM/GPU usage during this, and this happens even with only 60%/40%/47% utilization on the 3 as well. 

When it does happen, it tends to be partway through the processing of the response, usually 50-80% of the way through. I'm not really sure what could be going on here, so any assistance is appreciated. Example images are from the AMD machine

AMD machine specs: 
Processor	AMD Ryzen 5 3500X 6-Core Processor, 3600 Mhz, 6 Core(s), 6 Logical Processor(s)
BaseBoard Product	B550 Phantom Gaming 4/ac
Installed Physical Memory (RAM)	32.0 GB <<< DDR4
Total Virtual Memory	62.9 GB
AMD Radeon RX 5700 XT

Nvidia machine specs: 
Processor	Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz, 3401 Mhz, 4 Core(s), 4 Logical Processor(s)
BaseBoard Product	Z87 Killer
Installed Physical Memory (RAM)	32.0 GB <<< DDR3
Total Virtual Memory	47.9 GB
NVIDIA GeForce GTX 1070

Generic Error example
![Example 1](https://github.com/TavernAI/TavernAI/assets/149610632/62140bbd-f9dc-41e9-a88c-f9f095072099)

TavernAI CLI receiving response still after WebUI error example above
![Example 2 CMD tavern](https://github.com/TavernAI/TavernAI/assets/149610632/675958a4-44cf-4a9a-8ecc-a5eaa959ed1a)

Example of Server Busy error where TavernAI CLI still receives response even after the stated server busy error in both CLI and WebUI
![Server Busy example](https://github.com/TavernAI/TavernAI/assets/149610632/2b2bfd09-a438-4f5e-8547-7bb5a520946b)

**Comment by FunkEngine2023** [comment]
"Server is busy." Results from KoboldAI itself returning a 503 "service_unavailable" response to your outstanding api call to "/api/v1/generate" because that specific error text is being generated by KoboldAI and TavernAI is literally just printing the returned error string to the popup message area.


Why it waits for a while, then errors,  and still later on then seems to return the expected 200 "Successful" response including the text string content of GenerationResult is odd...

Let me noodle on this. Feel free to hit us up on the discord in the support channel. I'm going to take a closer examination of your screenshots now.


--Funk

**Comment by Waifuwars69** [comment]
> "Server is busy." Results from KoboldAI itself returning a 503 "service_unavailable" response to your outstanding api call to "/api/v1/generate" because that specific error text is being generated by KoboldAI and TavernAI is literally just printing the returned error string to the popup message area.
> 
> Why it waits for a while, then errors, and still later on then seems to return the expected 200 "Successful" response including the text string content of GenerationResult is odd...
> 
> Let me noodle on this. Feel free to hit us up on the discord in the support channel. I'm going to take a closer examination of your screenshots now.
> 
> --Funk

Sounds good. Let me know if you need any more information or the like from my end

**Comment by FunkEngine2023** [comment]
> Sounds good. Let me know if you need any more information or the like from my end


Can you show me the version details of the TavernAI you are running?  (F5 the tab,  scroll down Chloe's message, and it will be on the left side.)

Let's start with that.  Also, open up a powershell and give me a 'node -v' too, please.

**Comment by Waifuwars69** [comment]
> > Sounds good. Let me know if you need any more information or the like from my end
> 
> Can you show me the version details of the TavernAI you are running? (F5 the tab, scroll down Chloe's message, and it will be on the left side.)
> 
> Let's start with that. Also, open up a powershell and give me a 'node -v' too, please.

[@@@TavernAI v1.5.1@@@](https://github.com/TavernAI/TavernAI)


PS C:\Users\arhgh> node -v
v20.9.0
PS C:\Users\arhgh>

**Comment by FunkEngine2023** [comment]
> [@@@TavernAI v1.5.1@@@](https://github.com/TavernAI/TavernAI)
> 
> 
> PS C:\Users\arhgh> node -v
> v20.9.0
> PS C:\Users\arhgh>
> 
> 
> 
> 
> 

Okay, next thing is either the command line arguments you launch kcpp and / or KoboldAI's aiserver.py using, as well as essentially the settings you're using(either a whole lotta screenshots or the contents of 'customsettings.json, user_settings.v2-settings, and system_settings.v2-settings' etc (be sure to redact your horde API key etc before posting files. I think that's the only thing that's sensitive info in said files.)

I'm willing to go all the way to the bottom of this rabbit hole with you as I am involved with the KoboldAI/KoboldAI-Client project as well as working on TavernAI itself. Up to and including sniffing the packet traffic between KoboldAI and the TavernAI server.js node.exe process if necessary. (for the "Error!" Mostly. "Server is busy." Is definitely being generated by Kobold for some reason or another.)  Basically, you tell me when to give up on figuring out the actual problem. ![received_10155313670152404.jpeg](https://github.com/TavernAI/TavernAI/assets/123712145/6bfab124-0faa-47e1-b050-547b77891383)

**Comment by Waifuwars69** [comment]
> > [@@@TavernAI v1.5.1@@@](https://github.com/TavernAI/TavernAI)
> > PS C:\Users\arhgh> node -v
> > v20.9.0
> > PS C:\Users\arhgh>
> 
> Okay, next thing is either the command line arguments you launch kcpp and / or KoboldAI's aiserver.py using, as well as essentially the settings you're using(either a whole lotta screenshots or the contents of 'customsettings.json, user_settings.v2-settings, and system_settings.v2-settings' etc (be sure to redact your horde API key etc before posting files. I think that's the only thing that's sensitive info in said files.)
> 
> I'm willing to go all the way to the bottom of this rabbit hole with you as I am involved with the KoboldAI/KoboldAI-Client project as well as working on TavernAI itself. Up to and including sniffing the packet traffic between KoboldAI and the TavernAI server.js node.exe process if necessary. (for the "Error!" Mostly. "Server is busy." Is definitely being generated by Kobold for some reason or another.) Basically, you tell me when to give up on figuring out the actual problem. ![received_10155313670152404.jpeg](https://user-images.githubusercontent.com/123712145/279786061-6bfab124-0faa-47e1-b050-547b77891383.jpeg)

I've been mostly using the koboldcpp_nocuda version on my primary AMD machine but it happens with Koboldcpp and KoboldAI. I've been using koboldcpp and koboldcpp_nocuda as I found those more consistent to and easier to run for me (though I have done a build with the python bit on the NVIDIA machine which last used version 1.19.2 on local directory rather than B: drive,). As far as I'm aware I don't have any command line args set for either cpp version as I haven't really tried messing with them as they're .exe. 

If you need me to grab the contents of those settings files off the NVIDIA machine  or test putting the python version on the AMD machine I can it'll just take me a bit to do so.

**Comment by FunkEngine2023** [comment]
Kcpp should save the settings somewhere too, just screencap each pane of the settings panel on the kcpp ui.

Is your TavernAI installation on the same machine kcpp running on at the time? (Meaning you have node + TavernAI on both the ATI and the nVidia machines.)

Or are you running TavernAI on another machine and just poking kcpp via your wifi/LAN?

(Third comedy option, entirely possible nevertheless: You're running kcpp on one machine, TavernAI on another, and viewing the UI page(s) on a third entirely separate device.)



Also, I'm not sure what all / how detailed tracing is on Edge. Do either of these machines have Chrome/Firefox installed?

**Comment by Waifuwars69** [comment]
> Kcpp should save the settings somewhere too, just screencap each pane of the settings panel on the kcpp ui.
> 
> Is your TavernAI installation on the same machine kcpp running on at the time? (Meaning you have node + TavernAI on both the ATI and the nVidia machines.)
> 
> Or are you running TavernAI on another machine and just poking kcpp via your wifi/LAN?
> 
> (Third comedy option, entirely possible nevertheless: You're running kcpp on one machine, TavernAI on another, and viewing the UI page(s) on a third entirely separate device.)
> 
> Also, I'm not sure what all / how detailed tracing is on Edge. Do either of these machines have Chrome/Firefox installed?

I'll grab you a couple arrangements of the kcpp settings i've tried since i've tested a few of them. 

To clarify, each machine is standalone, running the programs needed on both. Though it would be pretty funny to split them like that. The Nvidia one is basically my old parts after upgrading my machine so I just opted to use it for various things instead of selling it, this being one of them. Originally I just used it since NVIDIA was the big AI thing, but I branched out to using my main later.

**Comment by FunkEngine2023** [comment]
![Screenshot_20231101_192836_Gallery](https://github.com/TavernAI/TavernAI/assets/123712145/53eb1ffe-1010-4fa3-ad01-3df4ca85708a)

Hoo boy! You should take a look at the dev version sometime...
![717-united1](https://github.com/TavernAI/TavernAI/assets/123712145/44ec7094-989f-4561-ad1b-2832828c142e)
A LOT has changed. Many much improvements yes.
![717-united2](https://github.com/TavernAI/TavernAI/assets/123712145/c43bca29-439c-454d-87cd-9efa054763cb)


What sort of models are you running on your rigs? (I know the nVidia has 8 gigs, I didn't look up the ATI VRAM...) 

I'm assuming you're running 7B size models, correct?

**Comment by FunkEngine2023** [comment]
> > Kcpp should save the settings somewhere too, just screencap each pane of the settings panel on the kcpp ui.
> > Is your TavernAI installation on the same machine kcpp running on at the time? (Meaning you have node + TavernAI on both the ATI and the nVidia machines.)
> > Or are you running TavernAI on another machine and just poking kcpp via your wifi/LAN?
> > (Third comedy option, entirely possible nevertheless: You're running kcpp on one machine, TavernAI on another, and viewing the UI page(s) on a third entirely separate device.)
> > Also, I'm not sure what all / how detailed tracing is on Edge. Do either of these machines have Chrome/Firefox installed?
> 
> I'll grab you a couple arrangements of the kcpp settings i've tried since i've tested a few of them.
> 
> To clarify, each machine is standalone, running the programs needed on both. Though it would be pretty funny to split them like that. The Nvidia one is basically my old parts after upgrading my machine so I just opted to use it for various things instead of selling it, this being one of them. Originally I just used it since NVIDIA was the big AI thing, but I branched out to using my main later.

Hit me up on the discord sometime and I'll run you through how to use tavern from a different machine on your lan/wifi from the one it is physically running on.  It makes keeping your cards/chats/settings etc synced really easy.  Same goes for getting the nVidia machine running "secret developer branch KoboldAI-Client" which can do some very new and amazing tricks that "Main, stable KoboldAI" (Especially for Windows! (Doubly especially for ATI ROCM Windows!)) can't.
(Either because they're broken in main, or haven't been released to main yet.)

**Comment by Waifuwars69** [comment]
> > > Kcpp should save the settings somewhere too, just screencap each pane of the settings panel on the kcpp ui.
> > > Is your TavernAI installation on the same machine kcpp running on at the time? (Meaning you have node + TavernAI on both the ATI and the nVidia machines.)
> > > Or are you running TavernAI on another machine and just poking kcpp via your wifi/LAN?
> > > (Third comedy option, entirely possible nevertheless: You're running kcpp on one machine, TavernAI on another, and viewing the UI page(s) on a third entirely separate device.)
> > > Also, I'm not sure what all / how detailed tracing is on Edge. Do either of these machines have Chrome/Firefox installed?
> > 
> > 
> > I'll grab you a couple arrangements of the kcpp settings i've tried since i've tested a few of them.
> > To clarify, each machine is standalone, running the programs needed on both. Though it would be pretty funny to split them like that. The Nvidia one is basically my old parts after upgrading my machine so I just opted to use it for various things instead of selling it, this being one of them. Originally I just used it since NVIDIA was the big AI thing, but I branched out to using my main later.
> 
> Hit me up on the discord sometime and I'll run you through how to use tavern from a different machine on your lan/wifi from the one it is physically running on. It makes keeping your cards/chats/settings etc synced really easy. Same goes for getting the nVidia machine running "secret developer branch KoboldAI-Client" which can do some very new and amazing tricks that "Main, stable KoboldAI" (Especially for Windows! (Doubly especially for ATI ROCM Windows!)) can't. (Either because they're broken in main, or haven't been released to main yet.)

Just want to let you know, haven't forgotten about getting you the info. Work just Kicked into high gear the last few days so I'll probably grab it on the weekend for you

**Comment by FunkEngine2023** [comment]
Reopen this when you're ready to follow up on this, and/or if you figured out the full root cause issue yourself.

--Funk
