### ISSUE TITLE
npm install problem

### ISSUE THREAD

**Issue by skaba04** [TavernAI/TavernAI-v1#240]
After running npm install on termux this happened, any idea how do i fix th
![Screenshot_20231110_172416_Termux](https://github.com/TavernAI/TavernAI/assets/116293460/c9c60818-a5b5-46d3-9d4e-5caea77b6972)

**Comment by Borov666** [comment]
It seems your actual node version is 20.2.0, you need 20.5.0 or higher

**Comment by skaba04** [comment]
What is the command on installation of node but version 20.5.0

**Comment by skaba04** [comment]
> What is the command on installation of node but version 20.5.0
Termux does not seem to find the version for nodejs.

**Comment by FunkEngine2023** [comment]
Just downgrade npm to 9.6.6...


`npm install -g npm@9.6.6`

**Comment by FunkEngine2023** [comment]
Also, you are going to need to either find or compile from source sharp/libvps...  If you wind up compiling them, please post them somewhere for others to find as well.
