### ISSUE TITLE
Is tawernAI still maintained

### ISSUE THREAD

**Issue by accessyapps** [TavernAI/TavernAI-v1#251]
Is tawern ai still maintained? Last update to release has been in november, also i saw another issue suggesting that it is not compatible with new oobabooga. Also in tawern ai there seams to be no option to start a new chat which in my opinion is really important for an ai chat app like that. I like working with tawern ai much more then with silly tawern since i am screenreader user and compared to tawern ai silly tawerns interface is a clusterfuck.

**Comment by FunkEngine2023** [comment]
![image](https://github.com/TavernAI/TavernAI/assets/123712145/23a69114-0bb5-44ae-bd71-9834fe731fd2)
![image](https://github.com/TavernAI/TavernAI/assets/123712145/e63ee2eb-5815-494e-afd5-634c8038df1d)


Version numbers only change when major things are added changesd... but the repo is constantly being updated/tweaked...  Install git or GHD and keep your local clone synced with the repo o always stay fresh...

**Comment by FunkEngine2023** [comment]
![Comparing @1 5 2 main · TavernAI_TavernAI (2)](https://github.com/TavernAI/TavernAI/assets/123712145/3ce6e0b2-2ee8-4dc4-8ff1-f93c1624e153)

**Comment by accessyapps** [comment]
The following 2 questions mait be stupid but i am new to this so sorry.
1. can i just run the repository like i would run the release?
2. Another thing. As i mentioned before there does not seam to be an option to start a new chat. Is this really the case or am i overseeing something?

**Comment by FunkEngine2023** [comment]
> The following 2 questions mait be stupid but i am new to this so sorry.
> 
> 1. can i just run the repository like i would run the release?
> 2. Another thing. As i mentioned before there does not seam to be an option to start a new chat. Is this really the case or am i overseeing something?

2: 
![image](https://github.com/TavernAI/TavernAI/assets/123712145/c17220cc-af56-4233-a8f9-85247c8dd660)


1: Yep! 
![image](https://github.com/TavernAI/TavernAI/assets/123712145/2597d7f7-b563-4c4a-a67a-f09076cc8c61)

https://discord.gg/zmK2gmr45t  Hop on discord if you need more help with setting up your local install to clone the repo

**Comment by accessyapps** [comment]
Can't deal with images since as i said, i am a screenreader user. But thanks for the discord link.
