### ISSUE TITLE
Link not generating and getting stuck at setting seed. (I hope I'm reporting this in the correct place idk what I'm doing)

### ISSUE THREAD

**Issue by GeoTheZodiac** [TavernAI/TavernAI-v1#253]
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       On  | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P8               9W /  69W |      0MiB / 15360MiB |      0%   E. Process |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
fatal: destination path '/content/KoboldAI' already exists and is not an empty directory.
Wed Feb  7 00:09:23 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       On  | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P8              10W /  69W |      0MiB / 15360MiB |      0%   E. Process |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
Colab Check: True, TPU: False
INFO       | __main__:<module>:732 - We loaded the following model backends: 
GooseAI
Legacy GPTQ
OpenAI
Horde
Read Only
KoboldAI API
KoboldAI Old Colab Method
KoboldCPP
Basic Huggingface
Huggingface
Huggingface MTJ
INFO       | __main__:general_startup:1447 - Running on Repo: https://github.com/henk717/KoboldAI Branch: united
MESSAGE    | Welcome to KoboldAI!
MESSAGE    | You have selected the following Model: NeverSleep/Noromaid-13b-v0.1.1
TODO: Allow config
INFO       | modeling.inference_models.hf:set_input_parameters:198 - {'0_Layers': 40, 'CPU_Layers': 0, 'Disk_Layers': 0, 'quantization': '4bit', 'id': 'NeverSleep/Noromaid-13b-v0.1.1', 'model': 'NeverSleep/Noromaid-13b-v0.1.1', 'path': None, 'menu_path': ''}
INIT       | Starting   | Flask
INIT       | OK         | Flask
INIT       | Starting   | Webserver
INIT       | OK         | Webserver
MESSAGE    | Webserver started! You may now connect with a browser at http://127.0.0.1:5000/
INIT       | Searching  | GPU support
INIT       | Found      | GPU support

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda122.so
/usr/local/lib/python3.10/dist-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /usr/lib64-nvidia did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/usr/local/lib/python3.10/dist-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events')}
  warn(msg)
/usr/local/lib/python3.10/dist-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('8013'), PosixPath('http'), PosixPath('//172.28.0.1')}
  warn(msg)
/usr/local/lib/python3.10/dist-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('//colab.research.google.com/tun/m/cc48301118ce562b961b3c22d803539adc1e0c19/gpu-t4-s-29aals2wowlyp --tunnel_background_save_delay=10s --tunnel_periodic_background_save_frequency=30m0s --enable_output_coalescing=true --output_coalescing_required=true'), PosixPath('--logtostderr --listen_host=172.28.0.12 --target_host=172.28.0.12 --tunnel_background_save_url=https')}
  warn(msg)
/usr/local/lib/python3.10/dist-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/datalab/web/pyright/typeshed-fallback/stdlib,/usr/local/lib/python3.10/dist-packages')}
  warn(msg)
/usr/local/lib/python3.10/dist-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/env/python')}
  warn(msg)
/usr/local/lib/python3.10/dist-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('//ipykernel.pylab.backend_inline'), PosixPath('module')}
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 7.5
CUDA SETUP: Detected CUDA version 122
CUDA SETUP: Loading binary /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda122.so...

Loading checkpoint shards:   0% 0/6 [00:00<?, ?it/s]/usr/local/lib/python3.10/dist-packages/transformers/utils/bitsandbytes.py:17: FutureWarning: transformers.utils.bitsandbytes module is deprecated and will be removed in a future version. Please import bitsandbytes modules directly from transformers.integrations
  warnings.warn(
Loading model tensors: 100%|##########| 68/68 [00:23<00:00,  2.52it/s]
Loading model tensors: 100%|##########| 70/70 [00:34<00:00,  2.50it/s]
Loading model tensors: 100%|##########| 70/70 [00:34<00:00,  2.54it/s]
Loading model tensors: 100%|##########| 69/69 [00:33<00:00,  2.22it/s]
Loading model tensors: 100%|##########| 71/71 [00:33<00:00,  2.45it/s]
Loading model tensors:  93%|#########3| 14/15 [00:08<00:00,  2.36it/s]
Loading checkpoint shards: 100% 6/6 [02:49<00:00, 28.29s/it]

generation_config.json: 100% 159/159 [00:00<00:00, 655kB/s]
Loading model tensors: 100%|##########| 15/15 [00:08<00:00,  1.70it/s]
tokenizer_config.json: 100% 1.12k/1.12k [00:00<00:00, 5.22MB/s]

tokenizer.model: 100% 500k/500k [00:00<00:00, 12.0MB/s]

added_tokens.json: 100% 21.0/21.0 [00:00<00:00, 73.0kB/s]

special_tokens_map.json: 100% 549/549 [00:00<00:00, 2.24MB/s]

tokenizer.json:   0% 0.00/1.84M [00:00<?, ?B/s]
tokenizer.json: 100% 1.84M/1.84M [00:00<00:00, 15.4MB/s]
INIT       | Starting   | LUA bridge
INIT       | OK         | LUA bridge
INIT       | Starting   | LUA Scripts
INIT       | OK         | LUA Scripts
2024-02-07 00:12:27.055799: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-02-07 00:12:27.055862: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-02-07 00:12:27.057387: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-02-07 00:12:29.615244: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Setting Seed

**Comment by FunkEngine2023** [comment]
Scroll up...

Click your tavern link.
![image](https://github.com/TavernAI/TavernAI/assets/123712145/df2156c9-1948-4df3-aba3-54000a3bfc2a)

Enjoy your tavern, which is fully loaded and running for however long you've been sitting there staring at Setting_Seed...

It should autoconnect, but if it doesn't head to settings, smack the reset to default button on the API url field, then hit connect.

![image](https://github.com/TavernAI/TavernAI/assets/123712145/9656f62c-750e-409e-97bb-46dcb0604dce)

--FunkEngine

**Comment by GeoTheZodiac** [comment]
I'll give this a try and let you know.

**Comment by FunkEngine2023** [comment]
Take a poke at the KCpp beta version colab we have now as well... (It loads both TavernAI **and** the model in... Under two minutes if you sign into drive quick enough.) :)  Works the same way as GPU.ipynb... Run tavern cell first, sign into drive, run the kobold(KCpp) cell at the very bottom, wait a minute or two, and scroll up just a tad in the bottom output pane to get your link.

https://github.com/TavernAI/TavernAI/blob/main/colab/TAI%E2%99%A5KCpp_RC_3.0.ipynb

![87](https://github.com/TavernAI/TavernAI/assets/123712145/21270c07-e648-4283-a751-e1b016ae2ea4)

**Comment by GeoTheZodiac** [comment]
Quick question. What if I wanna run tavernai locally?

**Comment by FunkEngine2023** [comment]
PC Mac or Linux?

Running TavernAI locally is easy on any of them, however running the actual LLM AI model inference back-end (Kobold, etc.) __locally__ may or may not be a thing that your GPU is actually capable of doing.  You might wind up still using colab to stand up a model on an API for you remotely, to use with your local tavern.

If you want to hop on discord for further discussion just @ me in the server. https://discord.gg/tgpPu247

**Comment by GeoTheZodiac** [comment]
Okay I'm in the server
