### ISSUE TITLE
No connection to CharaCloud

### ISSUE THREAD

**Issue by Mehmet2407** [TavernAI/TavernAI-v1#255]
Cannot connect to the character library. when I try the text below appears on the cmd window. I am using a windows PC, Nodejs on v21.7.1. and TavernAI version is 1.5.4. so everything is updated to the latest.

No connection to charaCloud
Error: connect ETIMEDOUT 168.100.10.69:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16) {
  errno: -4039,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '168.100.10.69',
  port: 443,
  request: ClientRequest {
    _events: [Object: null prototype] { error: [Function (anonymous)] },
    _eventsCount: 1,
    _maxListeners: undefined,
    href: 'https://tavernai.net/api/server/status',
    options: {
      host: 'tavernai.net',
      port: null,
      path: '/api/server/status',
      href: 'https://tavernai.net/api/server/status',
      method: 'GET',
      headers: {}
    },
    _httpRequest: Writable {
      _events: [Object],
      _writableState: [WritableState],
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _eventsCount: 2,
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [ClientRequest],
      _currentUrl: 'https://tavernai.net/api/server/status',
      [Symbol(shapeMode)]: true,
      [Symbol(kCapture)]: false
    },
    [Symbol(shapeMode)]: false,
    [Symbol(kCapture)]: false
  }
}

**Comment by Borov666** [comment]
I checked, the server is currently up and running.
