### ISSUE TITLE
Got trouble when upgrade to 1.25 version

### ISSUE THREAD

**Issue by oo2oo2pp1** [TavernAI/TavernAI-v1#26]
I can run the 1.13 version normally in my computer, and when I download the 1.25 version and run the start.bat, it kept crashed there.

![33](https://user-images.githubusercontent.com/55310834/215326072-06986622-5622-48b0-8387-cd82132dcaec.png)

When I use an older version of the file, it still works fine. Is it because I didn't completely delete the old version of the file?

**Comment by TavernAI** [comment]
You can try the build for windows (node js and all the necessary modules have already been compiled into one file) https://sourceforge.net/projects/tavernaimain/files/TavernAI.rar/download
