### ISSUE TITLE
My traven suddenly stopped working

### ISSUE THREAD

**Issue by yhxhww** [TavernAI/TavernAI-v1#264]
I've been using traven ai for nearly a year, but just three days ago, my tavern started to get stuck at 'No connection...', and there was no change to the source of my api key or anything else. Is this a problem that only I have? Is this a problem with the server or my network? How can I fix it?

**Comment by Borov666** [comment]
Need more info about your problem, are you using the local or colab version of TavernAI? And what specific api are you using (KoboldAI, NovelAI, etc)?

**Comment by yhxhww** [comment]
I'm using the web-based version of colab, KoboldAI, but I think I've found the possible cause of the problem.

I think it has to do with the stability of the network. I started working in other cities a few days ago, and I no longer use the network cable, but use wifi. So after I kept switching networks, I found that no matter how good the wifi signal was, Traven ai could never connect to the server.

So now, how should I use Traven ai without a network cable to the computer?

**Comment by Borov666** [comment]
To use locally you need to install the local version of TavernAI. And to run AI model you can use for example https://github.com/LostRuins/koboldcpp and model in gguf format. Only take into account that to run the model you need a fairly powerful computer.

**Comment by yhxhww** [comment]
OK, I downloaded the model locally and ran it.
