### ISSUE TITLE
deleting a character causes disconnect from KoboldAI API

### ISSUE THREAD

**Issue by Slug-Cat** [TavernAI/TavernAI-v1#29]
After connecting to the KoboldAI API via Kaggle notebook, deleting a character on TavernAI will cause a loss of connection to the API, and a reconnect is necessary. It's not a huge deal, but slightly annoying and kind of odd.
![image](https://user-images.githubusercontent.com/53411759/215605563-465665b1-71bc-4084-8039-d1933a32a109.png)
![image](https://user-images.githubusercontent.com/53411759/215605621-ac0cb95f-f400-474c-89b2-b2291ec824b4.png)
![image](https://user-images.githubusercontent.com/53411759/215605712-ba9ea147-941d-4477-b22a-45b89c835be5.png)

**Comment by TavernAI** [comment]
Taken into account. Planned for correction.

**Comment by RossAscends** [comment]
is this due to the page refreshing? some functions cause the page to auto reload (changing user's chat name, for example) so it could be that.
