### ISSUE TITLE
top_k/top_p/typical_p parameters

### ISSUE THREAD

**Issue by Yuugirihime** [TavernAI/TavernAI-v1#30]
Hello~! Can we somewhere change these parameters, i wonder?

**Comment by TavernAI** [comment]
Yes, in preset file settings "TavernAI\public\KoboldAI Settings". You can also enable the KoboldAI GUI mode and the settings will be taken from the KoboldAI interface.

**Comment by Borov666** [comment]
The function of changing these parameters has been added to the interface
