### ISSUE TITLE
i deleted a characters but some how the whole characters file is gone

### ISSUE THREAD

**Issue by gofding** [TavernAI/TavernAI-v1#31]
oh and the chats file, then now when ever i try to recreated my character the npm crash and close

**Comment by TavernAI** [comment]
Sorry, but it 's not quite clear. Do you mean, you deleted a character and all the characters disappeared? And what error do you get in the console when it crashes?

**Comment by V1nm4n** [comment]
Long story short: deleting character files via UI delete button should just move it to a "trash" directory to prevent issues like this.
