### ISSUE TITLE
Prompting bug when generating 100+token responses with Pygmalion

### ISSUE THREAD

**Issue by QM60** [TavernAI/TavernAI-v1#35]
Right now, when you call ```runGenerate(getMessage)``` to resume a generation, only the previous block of text is passed in to generate the new prompt.  This means that once output accumulates, the prompt will not be generated properly, which will make the model more incoherent than it should be.
As an example, suppose the model wants to generate A B C D where each letter is a block of 50 tokens and history is H.
It will get prompted with "H", "H A", "H B", "H C" and so on. Whereas it should be "H", "H A", "H A B", "H A B C".

This should be simple enough to reproduce, but Pygmalion responses can be fairly short which is why it probably wasn't caught yet. Once a long message is generating, the bug is easy to spot in the log.

I believe replacing that line with ```runGenerate(cycleGenerationPromt + getMessage);``` should be enough to fix this, and that change seems to work in cursory testing.

**Comment by Borov666** [comment]
Fixed https://github.com/TavernAI/TavernAI/commit/2b4e36340e80f582884f4ac8bfdca1a5b1ebf08a
