### ISSUE TITLE
Feature Request: Option for Silent Output

### ISSUE THREAD

**Issue by TarotFooling** [TavernAI/TavernAI-v1#39]
Kobold has the flag "--quiet" to hide responses in the log. I think Tavern should also have this option, or something similar. As it stands now any computer in the local network can access the TavernAI server and see your chats. Unless you do some firewall shenanigans that 99% of users won't know about. This would also make it easier to run TavernAI on any computer since privacy won't be as much of a  concern.

**Comment by TavernAI** [comment]
Planned solution:
1) Whitelist of ip addresses for server.js functions.
2) localhost is whitelisted by default.
3) Ability to disable-enable the whitelist

**Comment by Borov666** [comment]
Commit: https://github.com/TavernAI/TavernAI/commit/0a13b2da5339af33cf602de5d2feef2386608a6d The discussion is transferred here: https://github.com/TavernAI/TavernAI/issues/40
