### ISSUE TITLE
Feature Request: Add support for localtunnel

### ISSUE THREAD

**Issue by TarotFooling** [TavernAI/TavernAI-v1#4]
Using a localtunnel link from a kobold client crashes TavernAI as soon as you try to send any message.
Kobold has support for localtunnel, although it's use is only in fringe cases currently, I'd love to see support so we can use TavernAI on Paperspace.

**Comment by TavernAI** [comment]
I tested it and localtunel works fine. What error do you get when you crash TavernAI?

**Comment by TarotFooling** [comment]
Was my fault, wasn't using the latest version of Kobold.
Sorry for your time.
