### ISSUE TITLE
Feature Request: Kobold Horde Support

### ISSUE THREAD

**Issue by V1nm4n** [TavernAI/TavernAI-v1#41]
**Ability to connect to:**
1) The greater KoboldAI horde for use of the network without a GPU.

2) The ability to connect to the pair of local KoboldAI instances running, of which A) One instance is running a model being shares by the network, B) one instance is connected to the model running on the network to provide GPU power to the Horde.

This would enable 1) the ability for TavernAI to connect to models hosted in a decentralized manner, 2) Incentivize KoboldAI workers that host nodes to provide processing bandwidth since they can still use TavernAI rather than have to use the Kobald UI. 3) Allow Kobold to focus on network stability rather than having to develop features to match TavernAI, while allowing Tavern to focus on character creation/storage/prompt creation UX.

**Comment by TarotFooling** [comment]
Didn't they already do this?
https://github.com/TavernAI/TavernAI/issues/1

**Comment by V1nm4n** [comment]
I was told by Henky that it does not yet support, but if it does, a guide for the process would be appreciated. If someone walked me through it I could put together a basic guide.

EDIT: https://github.com/TavernAI/TavernAI/issues/1

Was previously posted but again, Henky said it didn't work and I wasn't able to locate anything between the two platforms, looking for clarity on what is/isn't supported.

**Comment by MarkSchmidty** [comment]
@TavernAI https://github.com/TavernAI/TavernAI/issues/1 appears incorrectly closed.

Anyway, here is a working fork of TavernAI with Horde support: https://github.com/TavernAI/TavernAI/compare/main...Aspartame-e951:TavernAI:main

**Comment by Borov666** [comment]
Horde support was added in 1.4.0
