### ISSUE TITLE
[Feature Request] Add support of <|endoftext|>

### ISSUE THREAD

**Issue by Silver267** [TavernAI/TavernAI-v1#47]
This is used by recent experiments of pygmalion, and it would be a useful feature to prevent new pygmalion experiments from breaking.

**Comment by TarotFooling** [comment]
This already seems to work correctly in 1.2.7 as long as you are using the new config, and are on the united branch of Kobold

**Comment by Silver267** [comment]
Update: solved by updating kobold backend to united.
