### ISSUE TITLE
Feature request: Text to speech

### ISSUE THREAD

**Issue by minipasila** [TavernAI/TavernAI-v1#5]
You should consider adding TTS using either NovelAI's own TTS system which I did see someone else use on some other project [here](https://github.com/discordia-space/CEV-Eris/pull/7342) or using like Google's TTS system which is pretty affordable [mostly free](https://cloud.google.com/text-to-speech/pricing) that I've seen working in another [project](https://gitlab.com/nolialsea/alicebot/-/tree/dev/). You could also use some other TTS system if there is one.

**Comment by TavernAI** [comment]
I took it on board. I think it will be implemented in the future.

**Comment by scythe000** [comment]
There's also a variety of open source AI-based TTS systems now

**Comment by tanfarou** [comment]
Tortoise TTS Fast is decent. On its fastest setting, it synthesizes a typical chat response in about 6 seconds with everything running simultaneously on a 3090. I hope we can integrate it programmatically.

**Comment by minipasila** [comment]
Fast tortoise on my RTX 3060 Ti takes about 40-70 seconds on the fastest settings to generate the example text "The expressiveness of autoregressive transformers is literally nuts! I absolutely adore them." also there's no way I'd be able to run both things at the same time, unless you use one of the APIs.

**Comment by rrikabuto** [comment]
I was using this, it's very fast at inference but requires previous finetuning for copying the voices.
https://github.com/Plachtaa/VITS-fast-fine-tuning

**Comment by minipasila** [comment]
VITS is pretty good, though I'm still playing around it to see if I can make it sound better. But as mentioned before the inference is very fast compared to tortoise-tts (this also seems to work on your cpu).

**Comment by nagolinc** [comment]
It would be even cooler if you could use https://huggingface.co/camenduru/one-shot-talking-face to generate videos of the characters talking like I do here: https://github.com/nagolinc/AnimeBuilder/blob/main/animeCreator.py#L565-L603

**Comment by alexanderwise** [comment]
I think [Azure Text-To-Speech](https://azure.microsoft.com/en-us/products/cognitive-services/text-to-speech) might be a pretty good option for users who lack their own hardware, or enough hardware to do both language ai and TTS. It's got a generous free tier, and is pay-go after that. It also does realtime processing of short text strings and has a [JS SDK](https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/text-to-speech). I'd be interested in trying to wire something like that up.
