### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by Zelprup** [TavernAI/TavernAI-v1#52]
![image](https://user-images.githubusercontent.com/125584668/219416493-d9576a08-c1a8-4256-9042-cc7c27d7b084.png)
Hello, I'm recently a new user of Tavern.AI and it worked yesterday but now when I open up TavernAi you can see the issue in the image above, Although I'm connected to the internet it's unable to connect. is this a regular occurrence or an issue?

**Comment by Cathie-486** [comment]
I think if you go to settings you can just press connect again at the api url thing
