### ISSUE TITLE
[Feature idea]

### ISSUE THREAD

**Issue by Hotohori** [TavernAI/TavernAI-v1#57]
I don't know how that could be best realized, but it could be nice if the AI could generate the first message by it's own. Maybe by sending the AI a first user message which directs the AI to a greeting message that is only send when you start a new chat and after the AI created the first message it got not send anymore on top of the chat history. Especially when you have a character with that you often start a new chat this could be an nice feature. You didn't need a complex first message every time and that actually is always the same.

**Comment by RossAscends** [comment]
This can be done by creating a character with a 'first message' of nothing but a single space. Leaving the first message box totally empty will result in it being filled in with 'Hello' by default. You'll have to force it to update by sending a blank prompt. But it will then send a second message with no context except what you put in the character description and/or example chats.
