### ISSUE TITLE
Works on Debian/Ubuntu 22.04.1 Linux

### ISSUE THREAD

**Issue by EchoesEqu** [TavernAI/TavernAI-v1#6]
It's strange that you haven't made a guide for working on the Linux... 
Or it works. 
"sudo apt install nodejs"
"sudo nodejs ./server.js" 
and that's it, we safely go to the link and play after setting up

**Comment by nonetrix** [comment]
Why are you running as root? Anyway on Arch Linux ```node ./server.js``` was enough

**Comment by Borov666** [comment]
A separate installer script has been added for Linux https://github.com/TavernAI/TavernAI/pull/70
