### ISSUE TITLE
Just Update new version and can't open Start.bat

### ISSUE THREAD

**Issue by Kaveid223** [TavernAI/TavernAI-v1#66]
TarvenAI use fine before i update it. After i update to new version and open Start.bat it give me a bunch of Error and shut itself 

here the error: 
C:\Program Files\nodejs>npm install
npm ERR! code EPERM
npm ERR! syscall mkdir
npm ERR! path C:\Program Files\nodejs\node_modules\.corepack-yRBjKBW1
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, mkdir 'C:\Program Files\nodejs\node_modules\.corepack-yRBjKBW1'
npm ERR!  [Error: EPERM: operation not permitted, mkdir 'C:\Program Files\nodejs\node_modules\.corepack-yRBjKBW1'] {
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'mkdir',
[2023-03-03T07_49_07_455Z-debug-0.log](https://github.com/TavernAI/TavernAI/files/10879371/2023-03-03T07_49_07_455Z-debug-0.log)

npm ERR!   path: 'C:\\Program Files\\nodejs\\node_modules\\.corepack-yRBjKBW1'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ventu\AppData\Local\npm-cache\_logs\2023-03-03T07_40_51_231Z-debug-0.log

**Comment by aibosan** [comment]
You don't have access rights to write into the directory, likely because you can't write into Program Files. Try it with administrator rights.

**Comment by Kaveid223** [comment]
> 

not work but i think i know why that happened 
because i install the main TavernAI folder straight into Node file. So i move tavernAI main folder out and it back to work! 
Thanks for replies !
