### ISSUE TITLE
Issue with NAI model Implementation

### ISSUE THREAD

**Issue by contentSkink** [TavernAI/TavernAI-v1#7]
While using NAI services like Krake, all stories have a hardlock and cannot continue after reaching the NAI token limit of 2048, as the system attempts to request a token size larger than the token limit in the system. [As seen here](https://imgur.com/a/3bdeyyb), the backend requests more tokens than the model is coded to handle, and fails the attempt.

**Comment by TavernAI** [comment]
I have made corrections, now there should not be such a error.

**Comment by gustojs** [comment]
Unfortunately the issue still exists on a fresh installation.
I can see that the app does cut from the request a chunk of messages that don't fit in the context anymore, but at some point the token amount still gets slightly higher than NAI's limit and the app errors out.

I've changed it locally for myself and it's working, but for others there might still be a need for a solution.

**Comment by TavernAI** [comment]
Added a temporary solution, I leave the thread open if there is a problem again. Later the problem will be solved properly
