### ISSUE TITLE
[Feature request] OpenAI's Official ChatGPT API support

### ISSUE THREAD

**Issue by minipasila** [TavernAI/TavernAI-v1#71]
They just recently released a new model in their API that uses ChatGPT which is essentially unfiltered version of ChatGPT, though it does cost money but not nearly as much as regular GPT-3 [(chatgpt $0.002/1K tokens vs gpt-3 $0.02/1K tokens)](https://openai.com/pricing) I've tried it a bit on a different UI but this one is a bit more easier to use.
[(also the UI I used had some other interesting stuff that uses OpenAI's APIs in that it supports a sort of long-term memory by summarizing some of the chat history)](https://github.com/michaelnutt02/my-chat-gpt)

**Comment by CncAnon1** [comment]
@minipasila there's an unofficial mod for it - https://rentry.org/tavernai_gpt35, it's not perfect, but I'll soon make a version based on a newer version of the older OpenAI mod.

More info about all that can be found on /aicg/ (i'm also usually there)

**Comment by Neutrovertido** [comment]
Support for OpenAI's GPT-3 would be most welcome indeed

**Comment by Neutrovertido** [comment]
it would also be nice to introduce the [free api workaround](https://github.com/ayaka14732/ChatGPTAPIFree), since it's available.

**Comment by CncAnon1** [comment]
> it would also be nice to introduce the [free api workaround](https://github.com/ayaka14732/ChatGPTAPIFree), since it's available.

it has a really low request per hour limit, and I doubt it'll be around for long.
