### ISSUE TITLE
BUG: backdrop-filter: blur(2px); causes high gpu usage

### ISSUE THREAD

**Issue by gtaltatra** [TavernAI/TavernAI-v1#72]
Please remove it's occurrences (in style.css)

**Comment by Silver267** [comment]
Turns out deleting this in the css solves #33.

**Comment by Borov666** [comment]
Solved in https://github.com/TavernAI/TavernAI/issues/33

**Comment by gtaltatra** [comment]
> Solved in 1.3.0
![xhCNEXscDXCN4SNMEgW1AwlicaYyZ6GIs9evDabV](https://user-images.githubusercontent.com/51547727/225611639-6a4c00a0-8581-48d1-a0d1-0aff3b864315.jpg)

No its not. Its still laggy as hell and the setting is still there. But apparently no one cares, lol. Okaay

**Comment by aibosan** [comment]
Commented out.
