### ISSUE TITLE
Add option to not use characloud as homepage in the webui

### ISSUE THREAD

**Issue by Silver267** [TavernAI/TavernAI-v1#75]
Title explains all.

**Comment by Rueby** [comment]
It's a cool feature for those who are interested in it but I'm really not interested in that...
I'll stick to 1.2.8 for now.

**Comment by MemeticGitHubUser** [comment]
This would be nice. Honestly I don't like being flashed with all that upon startup

**Comment by aibosan** [comment]
Made a settings toggle.
