### ISSUE TITLE
Long-term memory summarization

### ISSUE THREAD

**Issue by minipasila** [TavernAI/TavernAI-v1#76]
You should consider adding some sort of memory summarization to help achieve a sort of long-term memory so that even after you reach 4k tokens it would remember stuff beyond that.
Here is a [repository](https://github.com/michaelnutt02/my-chat-gpt) that has a few implementations of it using OpenAI's API.

**Comment by hpnyaggerman** [comment]
Sounds like something worth investigating

**Comment by scythe000** [comment]
I'd second this!

**Comment by brogowski** [comment]
Here is a quick prototype I've got running: https://github.com/TavernAI/TavernAI/compare/main...brogowski:TavernAI:main

@TavernAI let me know if you would like to have this feature in main.

**Comment by minipasila** [comment]
That works quite well but it will replace your actual conversation with the summary so you don't get to keep the original conversation. If the summary was somehow separated and kept the original conversation untouched (while knowing that it has summarized the earlier conversation) that'd be great. But otherwise it works really well.

**Comment by rosx27** [comment]
> Here is a quick prototype I've got running: [main...brogowski:TavernAI:main](https://github.com/TavernAI/TavernAI/compare/main...brogowski:TavernAI:main)
> 
> @TavernAI let me know if you would like to have this feature in main.

how to use this on tavernai? could you make a tutorial please?

**Comment by brogowski** [comment]
> > Here is a quick prototype I've got running: [main...brogowski:TavernAI:main](https://github.com/TavernAI/TavernAI/compare/main...brogowski:TavernAI:main)
> > @TavernAI let me know if you would like to have this feature in main.
> 
> how to use this on tavernai? could you make a tutorial please?

It's not implemented yet

**Comment by minipasila** [comment]
> > Here is a quick prototype I've got running: [main...brogowski:TavernAI:main](https://github.com/TavernAI/TavernAI/compare/main...brogowski:TavernAI:main)
> > @TavernAI let me know if you would like to have this feature in main.
> 
> how to use this on tavernai? could you make a tutorial please?

you just paste that code from the commit (green part) into the file **/TavernAI/public/script.js** and make sure you put it between these lines of code
```
            if(type == 'swipe'){
                chat2.shift();
            }
**paste it here**
            for (var item of chat2) {//console.log(encode("dsfs").length);
                chatString = item+chatString;
                if(getTokenCount(storyString+mesExmString+chatString+anchorTop+anchorBottom+charPersonality)+gap_holder < this_max_context){ //(The number of tokens in the entire prompt) need fix, it must count correctly (added +120, so that the description of the character does not hide)
```

**Comment by rosx27** [comment]
> > > Here is a quick prototype I've got running: [main...brogowski:TavernAI:main](https://github.com/TavernAI/TavernAI/compare/main...brogowski:TavernAI:main)
> > > @TavernAI let me know if you would like to have this feature in main.
> > 
> > 
> > how to use this on tavernai? could you make a tutorial please?
> 
> It's not implemented yet

is this for openai only? based on line 1041 onwards.

how can i implement this on using pygmalion-6b model?

**Comment by brogowski** [comment]
Pyg cannot do meaningful summarization in my experience.
We would need to find alternative API to do it for Pyg (or for all). 

Here is one that SillyTavern is using: https://huggingface.co/Qiliang/bart-large-cnn-samsum-ChatGPT_v3

**Comment by rosx27** [comment]
> Pyg cannot do meaningful summarization in my experience. We would need to find alternative API to do it for Pyg (or for all).
> 
> Here is one that SillyTavern is using: https://huggingface.co/Qiliang/bart-large-cnn-samsum-ChatGPT_v3

ohh thats too bad. ive been bashing my head around to implement your code into the pyg model using kobold api but ill still try to figure it out, maybe something will come up. ill try the model you provided tho. thank you!
