### ISSUE TITLE
Swiping sometimes generates entirely new messages instead of adding to the original message

### ISSUE THREAD

**Issue by MemeticGitHubUser** [TavernAI/TavernAI-v1#80]
The top message is the original message. Sometimes when swiping it turns into 3 dots and generates a new message below as seen here.
![image](https://user-images.githubusercontent.com/40185397/224853802-0e77c9ac-a3b6-4864-b1ca-72f2edf20f02.png)

**Comment by MemeticGitHubUser** [comment]
I just discovered that it only happens if the message before the one you are swiping is a message from the bot
![image](https://user-images.githubusercontent.com/40185397/224855917-855258bb-013f-4f09-8a9f-12aa823ee004.png)

**Comment by Borov666** [comment]
Fixed
