### ISSUE TITLE
Disconnecting

### ISSUE THREAD

**Issue by Whheat** [TavernAI/TavernAI-v1#85]
I get into a session on mobile using local tunnel and colab, and it works well for about 15 minutes then it disconnects forcing me to restart the whole setup. Great app though, all the charm of character.ai and none of the drawbacks 10/10.

**Comment by Whheat** [comment]
To clarify, it gives a red “no connection” error in the bottom left corner, I’m on iPhone and it isn’t the fault of service/WiFi.

**Comment by lmaoaiden** [comment]
same problem here. which collab link are you using?

**Comment by Whheat** [comment]
The one listed in GitHub, so I figured it out. Open tavernAI link in new tab, but if you’ve used it too much in a 12 hour period of time, it will fail to connect if you don’t pay for colab. Make sure to still have colab running in previous tab but tavernAI in new tab.

**Comment by FunkEngine2023** [comment]
Just re opening this to follow up with the reason **why** you all kept getting disconnected...

I believe I found the source of the issue, I definitely found the part where the wheels fell off over and over and over and over again and will be pushing my fix(es) to TavernAI/TavernAIColab main this week but for the meantime I will ask you phone chatters that run your TavernAI with your KoboldAI on the same box in the cloud to please kick the tires on my fixes, grab this sheet here https://colab.research.google.com/github/FunkEngine2023/TavernAIColab/blob/Funk-png/colab/GPU.ipynb

( My working branch is here for reference and feedback.) https://github.com/FunkEngine2023/TavernAIColab/tree/Funk-png

I fixed a buncha other long-time issues as well, so with luck, the mobile-moaning dies down to a sussurus....


![ftwtfghth.PNG](https://user-images.githubusercontent.com/123712145/229571984-d83d9e03-3d6d-42dd-a9f1-61371f383e6b.PNG)

![fugghincolab.PNG](https://user-images.githubusercontent.com/123712145/229571993-06a26207-e4c4-44ba-8f9f-37877da369d6.PNG)

![850359025715773491.png](https://user-images.githubusercontent.com/123712145/229572006-fd4e7803-146e-4c03-8b3c-8c89453e5df9.png)

So yeah...  It's a lot more stable than it previously was...


Loads nice and zippy as well. 

![229389606-fb04796b-d30c-40bb-99f6-fd642e6c89a8.PNG](https://user-images.githubusercontent.com/123712145/229572186-52d3a908-22da-4c51-b1b8-abb2db8ea0c6.PNG)

![229389607-d28a3090-267e-42d4-a7d7-fa409740aaa3.PNG](https://user-images.githubusercontent.com/123712145/229572214-7ede9f6d-c1b7-479c-977b-4fccb361b1bf.PNG)


7 minutes from push go to loading index.html in your browser,  39 times out of 40 on the first try...
