### ISSUE TITLE
Why is code so bad?

### ISSUE THREAD

**Issue by Enerccio** [TavernAI/TavernAI-v1#86]
Single massive file, why?

**Comment by aibosan** [comment]
Sometimes you write code to exact specification and plan thoroughly with a panel of experts. Sometimes you write code to just do the thing you want it to do. We plan on gradual refactoring.

**Comment by Enerccio** [comment]
Tak jo no :D

**Comment by FunkEngine2023** [comment]
> Single massive file, why?

exe wrapper bad, node installed good.
