### ISSUE TITLE
Something causes OpenAI to endlessely loop, burns through tokens 

### ISSUE THREAD

**Issue by Slug-Cat** [TavernAI/TavernAI-v1#87]
For some reason, when TavernAI is using OpenAI on gpt-3.5-turbo it will occassionally loop the same context infinitely without generating any output. This burns through OpenAI budget VERY quickly, as input costs the same in tokens as output, and each loop only takes around a second and there's no indication that anything is wrong in the UI itself. I think it only happens when enter is pressed without adding anything to context during a scenario. I think there should be a check or a limit to how many times TavernAI will retry a response so this doesn't occur. 
![image](https://user-images.githubusercontent.com/53411759/225521824-b172bdd6-3ed1-4b46-98d6-799bb681921b.png)

**Comment by Kamil118** [comment]
I have found the cause of the issue. On OpenAI side, it seems to sometimes return empty messages if it was trained filter some kinds of inputs. On the side of TavernAI:

In script.js on line 1385 the script checks if output message length isn't 0, and if it is, it repeats the generation with "force_name2" argument. This can repeat indefinitely and is only stopped when the user gets rate-limited by OpenAI.

The possible solution to this would be if on line 1417 before repeating the Generate the code checked if it doesn't already use "force_name2" type and show an error if it is. This would reduce the number of requests from tens to 2.
