### ISSUE TITLE
[FeatureRequest/Idea]: Ways to remember main plot-points

### ISSUE THREAD

**Issue by AllesMeins** [TavernAI/TavernAI-v1#88]
I noticed that sometimes TavernAi bots tend to get a bit "lost" and forget the scenario thus breaking the immersion. I was thinking how this might be improved and want to share with you my ideas for your consideration. I'm not really an expert on AI, so they might be stupid - but who knows :-)

It seems to me that some information are more important to remember than others to have a good conversation (and I might speculate that that is what character.AI does, because some info seems to stick around much longer than other). The current "mission/intension/goal" of the character comes to mind or the location/scenario where the conversation takes place. And I'm not talking about the character-definition but about something that might develop dynamically during the conversation. So it should be possible to make these key plot-points stick.

The **manual solution** might be to just give the user the opportunity to "pin" a few messages into memory. So if the character says "I want to visit the king" I could go *Yeah, that's important to the story, please keep that in mind*.

But it might also be possible to **do this automatically**. I was thinking whether one could add a small text-classification model into TavernAI that automatically detects lines that are specially relevant to the scenario and keeps them longer in memory. Such a simple classifier that just decides whether a "sentence describes intention/location" or not doesn't need that much computing power and should run on most systems.

What do you think? Have you already done some tests in this direction? Could this work?

**Comment by hpnyaggerman** [comment]
Related to https://github.com/TavernAI/TavernAI/issues/76 I am pretty sure

**Comment by aibosan** [comment]
A "notes" feature is currently under review.
