### ISSUE TITLE
Multiple User Profiles

### ISSUE THREAD

**Issue by rokelle2012** [TavernAI/TavernAI-v1#9]
After messing around with the software for a few hours, it seems that once the software is downloaded to the system, it assigns a singular user to it. That means all convos and characters are tied to this one user, no matter who is signed into Google Colab at the time. I share my PC with my partner. He and I do not have the same chat preferences and it would get tiring to have to constantly change the name of the user as well as save the current conversation and start a new one (especially with the fact that there is currently no way to actually load in a previous conversation into the UI).

**Comment by TarotFooling** [comment]
Just make a copy of the folder...

**Comment by rokelle2012** [comment]
Yes, I figured that out after I had already posted. Not very intuitive but it gets the job done.

**Comment by TavernAI** [comment]
I understand that for some users the multiuser function would be useful. However, at the moment, the introduction of such a function is not planned. I understand that this decision may not align with your expectations and I apologize for any inconvenience this may cause.

As mentioned above, at the moment, the best solution is to use different folders, for different users.
