### ISSUE TITLE
Allow special characters in prompt/characters

### ISSUE THREAD

**Issue by minipasila** [TavernAI/TavernAI-v1#96]
If I were to create a character in for example in my own native language Finnish it would replace all the Ä and Ö letters with A and O which can change the meaning of those words.. Also it does the same thing with emojis (OpenAI's API seems to be ok with those considering that I never had any problems with those in other UIs).

**Comment by Slug-Cat** [comment]
In ooba I can generate heart characters, tavern seems to replace them with a ? symbol. This is a needed feature.

**Comment by Borov666** [comment]
It was fixed in 1.4
