### ISSUE TITLE
Response time

### ISSUE THREAD

**Issue by NikolayWannaCode** [TavernAI/TavernAI-v1#97]
Hello.
Recently, the Spellbook's response time has dramatically lengthened. The tavern waits only 60 seconds, after which it issues an error. However, the Spellbook can sometimes give an answer after 2, 3, 5 minutes.

Is it possible to change tavern's waiting time?

**Comment by aibosan** [comment]
This could be made adjusted. Currently, the default timeout is used (which is a minute I think). I will see if I can implement a default in configuration that could be changed.

If you want to test it out, you can add `timeout` attribute to all ajax calls, set to the desired maximum in milliseconds. See: https://www.w3schools.com/jquery/ajax_ajax.asp

**Comment by aibosan** [comment]
@NikolayWannaCode The timeout should now be adjustable via `config.conf` constant `connectionTimeoutMS`. I've increased the default to 2 minutes. Please let me know if there are any issues.
[commit ce709869](https://github.com/TavernAI/TavernAI/commit/ce7098692b2ad83e6e185daf6fbe3c32007e4ee8)
[commit 22e41ca3](https://github.com/TavernAI/TavernAI/commit/22e41ca3ae10135cf8f8ef13788cc787b78e03d4)
