### ISSUE TITLE
Textbox Area Issue and Autoconnect to NAI Issue

### ISSUE THREAD

**Issue by Keerigan45** [TavernAI/TavernAI-v1#98]
Hey, the autoconnect to NovelAI API looks like he doesn't work and the message input area look very small i've tried different thing like changing browsers but i stil have the same error here are the screen 
![Capture](https://user-images.githubusercontent.com/104183492/226771415-19ae37eb-57a1-4ab6-8e43-4dcc957154ac.PNG)
![Capture2](https://user-images.githubusercontent.com/104183492/226771417-2541b81f-524f-4bbf-88fc-d3def4009610.PNG)

**Comment by aibosan** [comment]
@Keerigan45 Strange behavior, thanks for feedback!
Does NovelAI work with when connecting manually? The autoconnect might be trying before API key is restored, and failing because of that. I'll look into it.
As for the text box, if you know how, try to set the element's CSS width to 100% (it's commented out). And if you contact me directly on Discord or email I'm sure we can figure it out together!

**Comment by Keerigan45** [comment]
I'll set it to 100% or maybe i made a mistake somewhere but since it give me prompt i don't know what it can come

**Comment by Keerigan45** [comment]
Cuz interestingly sometime it goes to the center, sometime it goes left sometime it goes right

**Comment by aibosan** [comment]
@Keerigan45 It's very weird. But the layout leaves much to be desired at points. I think I can make a more proper fix, but I'd like to figure out why this doesn't work first.
What version of TAI are you running? 1.3.1 release?
What browser and version are you using?

**Comment by Keerigan45** [comment]
and now i can't connect anymore, and the lastest i think since i downloaded it from github

**Comment by Keerigan45** [comment]
I use vivaldi chromium based and Chrome too but it appear on both

**Comment by aibosan** [comment]
@Keerigan45 Try to update your `public\designs\classic.css` from the last commit I made please, to see if it works at all.

**Comment by Keerigan45** [comment]
I see that it's updated since 5 day, I'm downloading it and quick question do you think formalize Pygmalion even when using Krake is a good idea ?

**Comment by Keerigan45** [comment]
and adding preset or module could be interesting but i have to look into their APIS if there is something since it's on their server

**Comment by Keerigan45** [comment]
downloaded asked files still the same i've deactivate extension that could potentially alter css like adblock but i still get the same result TextInput goes right or lef

**Comment by aibosan** [comment]
That's definitely strange behavior... Are there any prohibited changes when you inspect the element? I thought positioning it absolutely would work...
Maybe it's not display: block by default or something?

**Comment by Keerigan45** [comment]
tho i can't see the commit on the css files you made so maybe it can come from this

**Comment by Keerigan45** [comment]
I got inline-block

**Comment by Keerigan45** [comment]
on textarea

**Comment by aibosan** [comment]
I definitely pushed it, it's https://github.com/TavernAI/TavernAI/commit/16c72d0e7c975f158150298cee2d5dedbf09f2b4

**Comment by aibosan** [comment]
Apparently, the problem with textarea comes from an extension called **ProWritingAID**.
